// Boulder Atlas seed data — the starting dataset of climbing spots.
// This is exposed as a global so app.js can read it without a bundler/module step.
// Add/rearrange entries here directly; app.js never needs to change for data edits.

  const IB = 'indoor-bouldering', TR = 'top-rope';

  window.SEED_GYMS = [
    // --- NSW / Sydney ---
    {name:"9 Degrees Alexandria", suburb:"Alexandria", state:"NSW", lat:-33.9042, lng:151.1968, types:[IB]},
    {name:"9 Degrees Lane Cove", suburb:"Lane Cove West", state:"NSW", lat:-33.8138, lng:151.1667, types:[IB]},
    {name:"9 Degrees Parramatta", suburb:"Rydalmere", state:"NSW", lat:-33.8153, lng:151.0270, types:[IB]},
    {name:"9 Degrees Waterloo", suburb:"Waterloo", state:"NSW", lat:-33.8994, lng:151.2094, types:[IB]},
    {name:"NOMAD Bouldering", suburb:"Annandale", state:"NSW", lat:-33.8853, lng:151.1706, types:[IB]},
    {name:"NOMAD Bouldering Gladesville", suburb:"Gladesville", state:"NSW", lat:-33.8332, lng:151.1276, types:[IB]},
    {name:"Sydney Indoor Climbing Gym – St Peters", suburb:"St Peters", state:"NSW", lat:-33.9098, lng:151.1804, types:[IB,TR]},
    {name:"Elevate Climbing Villawood", suburb:"Villawood", state:"NSW", lat:-33.8823, lng:150.9757, types:[IB,TR], notes:"Formerly Sydney Indoor Climbing Gym Villawood — one of the largest lead/top-rope venues in the country."},
    {name:"Climb Fit St Leonards", suburb:"St Leonards", state:"NSW", lat:-33.8230, lng:151.1953, types:[IB,TR]},
    {name:"Climb Fit Macquarie", suburb:"Macquarie Park", state:"NSW", lat:-33.7739, lng:151.1224, types:[IB,TR], notes:"Top rope + bouldering, but no lead routes."},
    {name:"Climb Fit Kirrawee", suburb:"Kirrawee", state:"NSW", lat:-34.0333, lng:151.0833, types:[IB,TR]},
    {name:"The Ledge Climbing Centre", suburb:"Camperdown", state:"NSW", lat:-33.8886, lng:151.1786, notes:"Sydney Uni's climbing club gym — top rope + bouldering, no lead.", types:[IB,TR]},
    {name:"The Edge Rock Climbing Centre", suburb:"Castle Hill", state:"NSW", lat:-33.7315, lng:150.9885, types:[IB,TR]},
    {name:"The Climbing Centre", suburb:"Penrith", state:"NSW", lat:-33.7530, lng:150.6890, types:[TR], notes:"Top rope only — no bouldering wall, no lead."},
    {name:"BlocHaus Marrickville", suburb:"Marrickville", state:"NSW", lat:-33.9111, lng:151.1547, types:[IB]},
    {name:"BlocHaus Leichhardt", suburb:"Leichhardt", state:"NSW", lat:-33.8834, lng:151.1567, types:[IB]},
    {name:"Beta One Bouldering Gym", suburb:"South Granville", state:"NSW", lat:-33.8391, lng:151.0090, types:[IB]},
    {name:"Climbing Collective", suburb:"Jamisontown", state:"NSW", lat:-33.7580, lng:150.6950, types:[IB]},
    {name:"1UP Bouldering", suburb:"Chullora", state:"NSW", lat:-33.8927, lng:151.0447, types:[IB]},
    {name:"Northern Beaches Rockhouse", suburb:"Brookvale", state:"NSW", lat:-33.7677, lng:151.2688, types:[IB,TR]},
    {name:"Skywood Climbing", suburb:"Freshwater", state:"NSW", lat:-33.7833, lng:151.2883, types:[IB]},
    {name:"Hangdog Climbing Gym", suburb:"Coniston", state:"NSW", lat:-34.4300, lng:150.8850, types:[IB], notes:"Unverified this pass — flag if the type mix is off."},
    {name:"Camp Street Climbing", suburb:"Katoomba", state:"NSW", lat:-33.7139, lng:150.3111, types:[IB], notes:"Unverified this pass — flag if the type mix is off."},
    {name:"Pulse Climbing", suburb:"Warners Bay", state:"NSW", lat:-32.9686, lng:151.6372, types:[IB], notes:"Unverified this pass — flag if the type mix is off."},
    {name:"Albury Indoor Rock Climbing", suburb:"Albury", state:"NSW", lat:-36.0737, lng:146.9135, types:[IB], notes:"Unverified this pass — flag if the type mix is off."},
    {name:"Dymonite North Wollongong", suburb:"North Wollongong", state:"NSW", lat:-34.4210, lng:150.8930, types:[IB], notes:"Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},
    {name:"Dynomite Albion Park Rail", suburb:"Albion Park Rail", state:"NSW", lat:-34.5680, lng:150.7890, types:[IB], notes:"Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},
    {name:"Sandbox Bouldering Gym", suburb:"Silverwater", state:"NSW", lat:-33.8390, lng:151.0540, types:[IB], notes:"Boards-only gym. Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},

    // --- ACT ---
    {name:"Mountain Strong", suburb:"Fyshwick", state:"ACT", lat:-35.3336, lng:149.1642, types:[IB]},
    {name:"BlocHaus Bouldering Canberra", suburb:"Fyshwick", state:"ACT", lat:-35.3340, lng:149.1660, types:[IB]},
    {name:"BlocHaus Bouldering Mitchell", suburb:"Mitchell", state:"ACT", lat:-35.2270, lng:149.1470, types:[IB]},

    // --- VIC / Melbourne ---
    {name:"Hardrock Climbing", suburb:"Melbourne CBD", state:"VIC", lat:-37.8136, lng:144.9631, types:[IB,TR]},
    {name:"Hardrock Climbing Company", suburb:"Nunawading", state:"VIC", lat:-37.8156, lng:145.1789, types:[IB,TR]},
    {name:"BlocHaus Bouldering", suburb:"Port Melbourne", state:"VIC", lat:-37.8397, lng:144.9330, types:[IB]},
    {name:"Bayside Rock Climbing", suburb:"Carrum Downs", state:"VIC", lat:-38.0866, lng:145.1667, types:[IB,TR]},
    {name:"Northside Boulders", suburb:"Brunswick", state:"VIC", lat:-37.7666, lng:144.9599, types:[IB]},
    {name:"Northside Boulders", suburb:"Northcote", state:"VIC", lat:-37.7708, lng:145.0000, types:[IB]},
    {name:"Urban Climb", suburb:"Collingwood", state:"VIC", lat:-37.8033, lng:144.9852, types:[IB,TR]},
    {name:"Urban Climb", suburb:"Blackburn", state:"VIC", lat:-37.8189, lng:145.1544, types:[IB,TR], notes:"$15M flagship — Australia's tallest lead wall at 17m."},
    {name:"Boulder Lab", suburb:"Ferntree Gully", state:"VIC", lat:-37.8817, lng:145.2836, types:[IB]},
    {name:"Gravity Worx", suburb:"Pascoe Vale", state:"VIC", lat:-37.7202, lng:144.9310, types:[IB,TR]},
    {name:"UP Climbing", suburb:"Balaclava", state:"VIC", lat:-37.8676, lng:145.0009, types:[IB]},
    {name:"La Roca Boulders", suburb:"Oakleigh South", state:"VIC", lat:-37.9245, lng:145.0919, types:[IB]},
    {name:"Boulder Project", suburb:"Prahran", state:"VIC", lat:-37.8501, lng:144.9909, types:[IB]},
    {name:"Cliffhanger Climbing Gym", suburb:"Altona North", state:"VIC", lat:-37.8283, lng:144.8365, types:[IB], notes:"Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},
    {name:"Rocket Climbing", suburb:"Footscray", state:"VIC", lat:-37.8009, lng:144.8994, types:[IB], notes:"Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},

    // --- QLD ---
    {name:"9 Degrees Bouldering", suburb:"Enoggera", state:"QLD", lat:-27.4167, lng:152.9833, types:[IB]},
    {name:"Urban Climb Milton", suburb:"Milton", state:"QLD", lat:-27.4685, lng:153.0028, types:[IB], notes:"Bouldering-focused — no lead/top-rope here, unlike other Urban Climb sites."},
    {name:"Urban Climb Newstead", suburb:"Newstead", state:"QLD", lat:-27.4523, lng:153.0432, types:[IB,TR]},
    {name:"Urban Climb West End", suburb:"West End", state:"QLD", lat:-27.4823, lng:153.0084, types:[IB,TR]},
    {name:"BOUNCE Hendra", suburb:"Hendra", state:"QLD", lat:-27.4204, lng:153.0592, types:[IB,TR], notes:"Formerly Urban Xtreme — rock climbing is now one zone inside a larger trampoline/ninja park."},
    {name:"Rockit Climbing Gym", suburb:"Warana", state:"QLD", lat:-26.7716, lng:153.1235, types:[IB,TR]},
    {name:"Core Climbing", suburb:"Carrara", state:"QLD", lat:-28.0028, lng:153.3676, types:[IB], notes:"Queensland's largest dedicated bouldering gym."},
    {name:"Bould Move", suburb:"Birtinya", state:"QLD", lat:-26.7847, lng:153.1266, types:[IB]},
    {name:"Alpine Indoor Climbing", suburb:"Robina", state:"QLD", lat:-28.0724, lng:153.3899, types:[IB], notes:"Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},
    {name:"Climb Toowoomba", suburb:"Toowoomba", state:"QLD", lat:-27.5598, lng:151.9507, types:[IB], notes:"Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},
    {name:"Crank", suburb:"Macgregor", state:"QLD", lat:-27.5470, lng:153.0530, types:[IB], notes:"Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},
    {name:"Rocksports", suburb:"Fortitude Valley", state:"QLD", lat:-27.4560, lng:153.0345, types:[IB], notes:"Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},
    {name:"Rocky Climb", suburb:"Rockhampton", state:"QLD", lat:-23.3791, lng:150.5100, types:[IB], notes:"Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},
    {name:"SIX Degrees Bouldering Gym", suburb:"Atherton", state:"QLD", lat:-17.2667, lng:145.4800, types:[IB], notes:"Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},
    {name:"Urban Xtreme", suburb:"Hendra", state:"QLD", lat:-27.4090, lng:153.0670, types:[IB], notes:"A different gym from BOUNCE Hendra, also in this suburb. Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},

    // --- WA / Perth ---
    {name:"Adrenaline Vault", suburb:"Belmont", state:"WA", lat:-31.9581, lng:115.9297, types:[IB,TR], notes:"Largest indoor climbing centre in Perth."},
    {name:"Rockface", suburb:"Northbridge", state:"WA", lat:-31.9459, lng:115.8555, types:[IB,TR]},
    {name:"City Summit", suburb:"Malaga", state:"WA", lat:-31.8628, lng:115.8949, types:[IB]},
    {name:"Portside Boulders", suburb:"O'Connor", state:"WA", lat:-32.0525, lng:115.7883, types:[IB]},
    {name:"Portside Boulders", suburb:"Osborne Park", state:"WA", lat:-31.8945, lng:115.8202, types:[IB]},
    {name:"Rockface", suburb:"Balcatta", state:"WA", lat:-31.8636, lng:115.8296, types:[IB], notes:"A different Rockface location from the Northbridge one above. Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},
    {name:"The Boulder Hub", suburb:"Wangara", state:"WA", lat:-31.7910, lng:115.8250, types:[IB], notes:"Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},
    {name:"Urban Jungle", suburb:"Spearwood", state:"WA", lat:-32.1150, lng:115.7690, types:[IB], notes:"Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},

    // --- SA / Adelaide ---
    {name:"Adelaide's Bouldering Club (BoulderZone)", suburb:"Thebarton", state:"SA", lat:-34.9186, lng:138.5749, types:[IB]},
    {name:"Beyond Bouldering", suburb:"Kent Town", state:"SA", lat:-34.9195, lng:138.6180, types:[IB]},
    {name:"Beyond Bouldering", suburb:"Keswick", state:"SA", lat:-34.9391, lng:138.5751, types:[IB]},
    {name:"Beyond Bouldering", suburb:"Clovelly Park", state:"SA", lat:-35.0170, lng:138.5658, types:[IB]},
    {name:"Vertical Reality Climbing", suburb:"Holden Hill", state:"SA", lat:-34.8560, lng:138.6583, types:[IB,TR], notes:"Adelaide's only rope-climbing gym."},
    {name:"Southern Boulder", suburb:"Hope Forest", state:"SA", lat:-35.2833, lng:138.6167, types:[IB]},

    // --- TAS ---
    {name:"Beta Park", suburb:"Invermay", state:"TAS", lat:-41.4285, lng:147.1425, types:[IB], notes:"Launceston. Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},
    {name:"Rock It Climbing Centre", suburb:"Hobart", state:"TAS", lat:-42.8806, lng:147.3250, types:[IB], notes:"Sourced from Mountain Project's gym directory — suburb-level position, not an exact address."},

    // --- US indoor gyms ---
    {name:"Movement Boulder", suburb:"Boulder", state:"CO", country:"US", lat:40.0177, lng:-105.2508, types:[IB,TR]},
    {name:"Movement Baker", suburb:"Denver", state:"CO", country:"US", lat:39.7211, lng:-104.9925, types:[IB,TR]},
    {name:"Adventure Unlimited Rock Gym", suburb:"Buena Vista", state:"CO", country:"US", lat:38.8422, lng:-106.1310, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Ascent Studio", suburb:"Fort Collins", state:"CO", country:"US", lat:40.5853, lng:-105.0844, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Basecamp Bouldering", suburb:"Ouray", state:"CO", country:"US", lat:38.0231, lng:-107.6714, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Boulder Rock Club", suburb:"Boulder", state:"CO", country:"US", lat:40.0130, lng:-105.2650, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"CityRock Colorado Springs", suburb:"Colorado Springs", state:"CO", country:"US", lat:38.8339, lng:-104.8214, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Denver Bouldering Club", suburb:"Denver", state:"CO", country:"US", lat:39.7392, lng:-104.9903, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Denver Bouldering Club North", suburb:"Thornton", state:"CO", country:"US", lat:39.8680, lng:-104.9719, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Denver Bouldering Club South", suburb:"Sheridan", state:"CO", country:"US", lat:39.6403, lng:-105.0286, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Eagle Climbing + Fitness", suburb:"Eagle", state:"CO", country:"US", lat:39.6553, lng:-106.8287, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Epic Climbing Gym", suburb:"Estes Park", state:"CO", country:"US", lat:40.3772, lng:-105.5217, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"G1 Climbing + Fitness", suburb:"Broomfield", state:"CO", country:"US", lat:39.9205, lng:-105.0866, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Grand Valley Climbing", suburb:"Grand Junction", state:"CO", country:"US", lat:39.0680, lng:-108.5540, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Gravity Lab", suburb:"Durango", state:"CO", country:"US", lat:37.2790, lng:-107.8830, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Greeley Climbing Collective", suburb:"Greeley", state:"CO", country:"US", lat:40.4233, lng:-104.7091, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Grip Bouldering", suburb:"Grand Junction", state:"CO", country:"US", lat:39.0600, lng:-108.5470, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Gripstone Climbing and Fitness", suburb:"Colorado Springs", state:"CO", country:"US", lat:38.8480, lng:-104.7300, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Longmont Climbing Collective", suburb:"Longmont", state:"CO", country:"US", lat:40.1672, lng:-105.1019, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Loveland Climbing Collective", suburb:"Loveland", state:"CO", country:"US", lat:40.3978, lng:-105.0748, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Centennial", suburb:"Centennial", state:"CO", country:"US", lat:39.5807, lng:-104.8772, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Englewood", suburb:"Englewood", state:"CO", country:"US", lat:39.6478, lng:-104.9878, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Golden", suburb:"Golden", state:"CO", country:"US", lat:39.7555, lng:-105.2211, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement RiNo", suburb:"Denver", state:"CO", country:"US", lat:39.7660, lng:-104.9800, types:[IB,TR], notes:"RiNo neighborhood. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Pure Bouldering", suburb:"Colorado Springs", state:"CO", country:"US", lat:38.8220, lng:-104.8330, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Springs Climbing Center", suburb:"Colorado Springs", state:"CO", country:"US", lat:38.8600, lng:-104.8100, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Steamboat Climbing Collective", suburb:"Steamboat Springs", state:"CO", country:"US", lat:40.4850, lng:-106.8317, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Summit Climbing Gym", suburb:"Silverthorne", state:"CO", country:"US", lat:39.6308, lng:-106.0731, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Rock Lounge", suburb:"Durango", state:"CO", country:"US", lat:37.2720, lng:-107.8770, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Spot – Boulder", suburb:"Boulder", state:"CO", country:"US", lat:40.0190, lng:-105.2770, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Spot – Denver", suburb:"Denver", state:"CO", country:"US", lat:39.7150, lng:-105.0000, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Spot Golden", suburb:"Golden", state:"CO", country:"US", lat:39.7500, lng:-105.2150, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Spot Louisville", suburb:"Louisville", state:"CO", country:"US", lat:39.9778, lng:-105.1319, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Spot Thornton", suburb:"Thornton", state:"CO", country:"US", lat:39.8720, lng:-104.9650, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Übergrippen Indoor Climbing Crag", suburb:"Castle Rock", state:"CO", country:"US", lat:39.3722, lng:-104.8561, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Whetstone", suburb:"Fort Collins", state:"CO", country:"US", lat:40.5800, lng:-105.0900, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Bouldering Project Somerville", suburb:"Somerville", state:"MA", country:"US", lat:42.3876, lng:-71.0995, types:[IB,TR], notes:"Formerly Brooklyn Boulders Somerville, rebranded to Bouldering Project."},
    {name:"Brooklyn Boulders Chicago", suburb:"West Loop, Chicago", state:"IL", country:"US", lat:41.8819, lng:-87.6648, types:[IB,TR]},
    {name:"Boneyard Boulders", suburb:"Champaign", state:"IL", country:"US", lat:40.1164, lng:-88.2434, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Climb On", suburb:"Homewood", state:"IL", country:"US", lat:41.5586, lng:-87.6614, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"First Ascent – Arlington Heights", suburb:"Arlington Heights", state:"IL", country:"US", lat:42.0884, lng:-87.9806, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"First Ascent – Block 37", suburb:"Chicago", state:"IL", country:"US", lat:41.8836, lng:-87.6280, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"First Ascent – Humboldt Park", suburb:"Chicago", state:"IL", country:"US", lat:41.9050, lng:-87.7020, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"First Ascent – Peoria", suburb:"Peoria", state:"IL", country:"US", lat:40.6936, lng:-89.5890, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"First Ascent – Uptown", suburb:"Chicago", state:"IL", country:"US", lat:41.9670, lng:-87.6580, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"First Ascent Avondale", suburb:"Chicago", state:"IL", country:"US", lat:41.9390, lng:-87.7110, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Horizon Climbing", suburb:"Champaign", state:"IL", country:"US", lat:40.1050, lng:-88.2550, types:[IB], notes:"A different gym from Boneyard Boulders, also in Champaign. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Lincoln Park", suburb:"Chicago", state:"IL", country:"US", lat:41.9250, lng:-87.6520, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Wrigleyville", suburb:"Chicago", state:"IL", country:"US", lat:41.9484, lng:-87.6553, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"North Wall", suburb:"Crystal Lake", state:"IL", country:"US", lat:42.2411, lng:-88.3162, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Off Belay Rock Club", suburb:"Chicago", state:"IL", country:"US", lat:41.9080, lng:-87.6650, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Old Town Indoor Rock Climbing", suburb:"Chicago", state:"IL", country:"US", lat:41.9120, lng:-87.6380, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Rockaway Climbing Wall", suburb:"Batavia", state:"IL", country:"US", lat:41.8503, lng:-88.3126, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Proving Ground Bouldering Gym", suburb:"Normal", state:"IL", country:"US", lat:40.5142, lng:-88.9906, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Upper Limits", suburb:"Bloomington", state:"IL", country:"US", lat:40.4842, lng:-88.9937, types:[IB,TR], notes:"A different gym from The Proving Ground, also in the Bloomington-Normal area. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Urbana Boulders", suburb:"Urbana", state:"IL", country:"US", lat:40.1106, lng:-88.2073, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Vertical Endeavors – Glendale Heights", suburb:"Glendale Heights", state:"IL", country:"US", lat:41.9161, lng:-88.0770, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Austin Bouldering Project – Springdale", suburb:"Austin", state:"TX", country:"US", lat:30.2686, lng:-97.7031, types:[IB,TR]},
    {name:"arch", suburb:"Amarillo", state:"TX", country:"US", lat:35.2220, lng:-101.8313, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Armadillo Boulders", suburb:"San Antonio", state:"TX", country:"US", lat:29.6200, lng:-98.4300, types:[IB], notes:"US-281 location. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Armadillo Boulders – Camden St", suburb:"San Antonio", state:"TX", country:"US", lat:29.4400, lng:-98.4750, types:[IB], notes:"A different Armadillo Boulders location from the US-281 one above. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Armadillo Boulders – San Marcos", suburb:"San Marcos", state:"TX", country:"US", lat:29.8833, lng:-97.9414, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Austin Bouldering Project Westgate", suburb:"Austin", state:"TX", country:"US", lat:30.2450, lng:-97.8100, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Basin Climbing", suburb:"Hewitt", state:"TX", country:"US", lat:31.4638, lng:-97.1522, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Boulders Sport Climbing Center", suburb:"Harker Heights", state:"TX", country:"US", lat:31.0788, lng:-97.6578, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Canyons Rock Climbing", suburb:"Frisco", state:"TX", country:"US", lat:33.1507, lng:-96.8236, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Cave Climbing Gym", suburb:"El Paso", state:"TX", country:"US", lat:31.7700, lng:-106.4950, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Climb Capuchin", suburb:"Houston", state:"TX", country:"US", lat:29.8050, lng:-95.4700, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"CLIMB Woodlands", suburb:"The Woodlands", state:"TX", country:"US", lat:30.1658, lng:-95.4613, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Crux Climbing Center", suburb:"Austin", state:"TX", country:"US", lat:30.2350, lng:-97.7550, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Crux Climbing Center Central", suburb:"Austin", state:"TX", country:"US", lat:30.3050, lng:-97.7150, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Crux Climbing Center Pflugerville", suburb:"Pflugerville", state:"TX", country:"US", lat:30.4394, lng:-97.6200, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Dyno-Rock", suburb:"Arlington", state:"TX", country:"US", lat:32.7357, lng:-97.1081, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Elevator Rock", suburb:"Wichita Falls", state:"TX", country:"US", lat:33.9137, lng:-98.4934, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Inspire Cypress", suburb:"Cypress", state:"TX", country:"US", lat:29.9691, lng:-95.6972, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"InSPIRE Rock Lubbock", suburb:"Lubbock", state:"TX", country:"US", lat:33.5779, lng:-101.8552, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Inspire Spring", suburb:"Spring", state:"TX", country:"US", lat:30.0799, lng:-95.4172, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Mesa Rim Austin", suburb:"Austin", state:"TX", country:"US", lat:30.2900, lng:-97.6900, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Momentum – Katy", suburb:"Katy", state:"TX", country:"US", lat:29.7858, lng:-95.8244, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Momentum Silver Street", suburb:"Houston", state:"TX", country:"US", lat:29.7750, lng:-95.4050, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Dallas – The Hill", suburb:"Dallas", state:"TX", country:"US", lat:32.7900, lng:-96.7600, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Denton", suburb:"Denton", state:"TX", country:"US", lat:33.2148, lng:-97.1331, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Design District", suburb:"Dallas", state:"TX", country:"US", lat:32.7900, lng:-96.8300, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Fort Worth", suburb:"Fort Worth", state:"TX", country:"US", lat:32.7555, lng:-97.3308, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Grapevine", suburb:"Grapevine", state:"TX", country:"US", lat:32.9343, lng:-97.0781, types:[IB,TR], notes:"Formerly Summit. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Plano", suburb:"Plano", state:"TX", country:"US", lat:33.0198, lng:-96.6989, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"North Austin Rock Gym", suburb:"Austin", state:"TX", country:"US", lat:30.3800, lng:-97.7300, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Oso Climbing Gyms", suburb:"Dallas", state:"TX", country:"US", lat:32.7900, lng:-96.8100, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Power Spot Climbing", suburb:"Austin", state:"TX", country:"US", lat:30.2650, lng:-97.7050, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Sessions Climbing & Fitness", suburb:"El Paso", state:"TX", country:"US", lat:31.8300, lng:-106.5400, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Siloville Climbing Gym", suburb:"Hico", state:"TX", country:"US", lat:31.9846, lng:-98.0339, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Space City Rock Climbing Gym", suburb:"League City", state:"TX", country:"US", lat:29.5075, lng:-95.0949, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Stone Co. Climbing", suburb:"College Station", state:"TX", country:"US", lat:30.6280, lng:-96.3344, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Stone Moves Indoor Rock Climbing Gym", suburb:"Houston", state:"TX", country:"US", lat:29.9000, lng:-95.5300, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Summit Carrollton", suburb:"Carrollton", state:"TX", country:"US", lat:32.9756, lng:-96.8899, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Summit Denton", suburb:"Denton", state:"TX", country:"US", lat:33.1950, lng:-97.1500, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The District", suburb:"San Antonio", state:"TX", country:"US", lat:29.4500, lng:-98.4700, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Vertical World Seattle", suburb:"Magnolia, Seattle", state:"WA", country:"US", lat:47.6425, lng:-122.3988, types:[IB,TR], notes:"America's first indoor climbing gym, opened 1987."},
    {name:"Bloc Yard Bouldering Gym", suburb:"Spokane", state:"WA", country:"US", lat:47.6650, lng:-117.4260, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Castle Climbing Club", suburb:"Seattle", state:"WA", country:"US", lat:47.5400, lng:-122.3450, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Cirque Climbing", suburb:"Lacey", state:"WA", country:"US", lat:47.0343, lng:-122.8232, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Climb NORA", suburb:"Federal Way", state:"WA", country:"US", lat:47.3223, lng:-122.3126, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Climb Tacoma", suburb:"Tacoma", state:"WA", country:"US", lat:47.2400, lng:-122.4500, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Edgeworks Bellevue", suburb:"Bellevue", state:"WA", country:"US", lat:47.6250, lng:-122.1600, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Edgeworks Climbing Bel-Red", suburb:"Bellevue", state:"WA", country:"US", lat:47.6280, lng:-122.1550, types:[IB,TR], notes:"A different Edgeworks location from the one above. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Edgeworks Tacoma", suburb:"Tacoma", state:"WA", country:"US", lat:47.2650, lng:-122.4600, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Edgeworks Seattle", suburb:"Seattle", state:"WA", country:"US", lat:47.6100, lng:-122.3200, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Endurance Climbing Gym", suburb:"Burlington", state:"WA", country:"US", lat:48.4762, lng:-122.3260, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Half Moon Bouldering", suburb:"Seattle", state:"WA", country:"US", lat:47.6700, lng:-122.3650, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"High Steppe Climbing Center", suburb:"Yakima", state:"WA", country:"US", lat:46.6021, lng:-120.5059, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Insight Climbing and Movement", suburb:"Bainbridge Island", state:"WA", country:"US", lat:47.6262, lng:-122.5212, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Momentum Indoor Climbing – SODO", suburb:"Seattle", state:"WA", country:"US", lat:47.5750, lng:-122.3300, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Riverfront Rock Gym", suburb:"Wenatchee", state:"WA", country:"US", lat:47.4235, lng:-120.3103, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Rock Shop", suburb:"Richland", state:"WA", country:"US", lat:46.2857, lng:-119.2845, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Seattle Bouldering Project", suburb:"Seattle", state:"WA", country:"US", lat:47.5820, lng:-122.3120, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Seattle Bouldering Project – Fremont", suburb:"Seattle", state:"WA", country:"US", lat:47.6510, lng:-122.3500, types:[IB], notes:"Fremont neighborhood. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Seattle Bouldering Project – U-District", suburb:"Seattle", state:"WA", country:"US", lat:47.6610, lng:-122.3130, types:[IB], notes:"University District. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Seattle Bouldering Project – Upper Walls", suburb:"Seattle", state:"WA", country:"US", lat:47.5900, lng:-122.3200, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Source Climbing Center", suburb:"Vancouver", state:"WA", country:"US", lat:45.6387, lng:-122.6615, types:[IB,TR], notes:"Vancouver, WA (not BC). Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Summit Everett", suburb:"Everett", state:"WA", country:"US", lat:47.9790, lng:-122.2021, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Uplift Climbing", suburb:"Shoreline", state:"WA", country:"US", lat:47.7557, lng:-122.3415, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Vertical World North", suburb:"Lynnwood", state:"WA", country:"US", lat:47.8209, lng:-122.3151, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Vital Climbing Gym", suburb:"Bellingham", state:"WA", country:"US", lat:48.7519, lng:-122.4787, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Wild Walls, Inc.", suburb:"Spokane", state:"WA", country:"US", lat:47.6600, lng:-117.4300, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Sender One Climbing – LAX", suburb:"Los Angeles", state:"CA", country:"US", lat:33.9447, lng:-118.3859, types:[IB,TR]},
    {name:"Planet Granite San Francisco", suburb:"Presidio, San Francisco", state:"CA", country:"US", lat:37.8014, lng:-122.4668, types:[IB,TR]},
    {name:"The Cliffs at LIC", suburb:"Long Island City", state:"NY", country:"US", lat:40.7503, lng:-73.9425, types:[IB,TR], notes:"One of NYC's largest climbing gyms."},
    {name:"A.I.R. – Albany's Indoor Rock Gym", suburb:"Albany", state:"NY", country:"US", lat:42.6526, lng:-73.7562, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"B.C's Climbing", suburb:"New Paltz", state:"NY", country:"US", lat:41.7476, lng:-74.0857, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Brooklyn Bouldering Project", suburb:"Brooklyn", state:"NY", country:"US", lat:40.6900, lng:-73.9500, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Brooklyn Boulders Queensbridge", suburb:"Queens", state:"NY", country:"US", lat:40.7550, lng:-73.9450, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Brooklyn Uprising", suburb:"Brooklyn", state:"NY", country:"US", lat:40.6650, lng:-73.9900, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Cayuga Climbs", suburb:"Ithaca", state:"NY", country:"US", lat:42.4430, lng:-76.5019, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym", suburb:"Manhattan", state:"NY", country:"US", lat:40.7770, lng:-73.9880, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym (Buffalo)", suburb:"Buffalo", state:"NY", country:"US", lat:42.8864, lng:-78.8784, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym (Rochester)", suburb:"Rochester", state:"NY", country:"US", lat:43.1500, lng:-77.6150, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Chelsea", suburb:"Manhattan", state:"NY", country:"US", lat:40.7460, lng:-74.0020, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Troy", suburb:"Troy", state:"NY", country:"US", lat:42.7284, lng:-73.6918, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym Syracuse", suburb:"Syracuse", state:"NY", country:"US", lat:43.0481, lng:-76.1474, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"City Climbers Club (59th Street Gym)", suburb:"Manhattan", state:"NY", country:"US", lat:40.7670, lng:-73.9850, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Climbing Cave", suburb:"Queensbury", state:"NY", country:"US", lat:43.3480, lng:-73.6750, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Cornerstone Climbing", suburb:"Saratoga Springs", state:"NY", country:"US", lat:43.0831, lng:-73.7846, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"GP81", suburb:"Brooklyn", state:"NY", country:"US", lat:40.7050, lng:-73.9200, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Hudson Boulders", suburb:"Latham", state:"NY", country:"US", lat:42.7401, lng:-73.7565, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Island Rock Gym", suburb:"Plainview", state:"NY", country:"US", lat:40.7765, lng:-73.4787, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"MetroRock Bushwick", suburb:"Brooklyn", state:"NY", country:"US", lat:40.6958, lng:-73.9171, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Gowanus", suburb:"Brooklyn", state:"NY", country:"US", lat:40.6740, lng:-73.9880, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Harlem", suburb:"Manhattan", state:"NY", country:"US", lat:40.8116, lng:-73.9465, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement LIC", suburb:"Queens", state:"NY", country:"US", lat:40.7450, lng:-73.9400, types:[IB,TR], notes:"Long Island City — a different gym from The Cliffs at LIC, above. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Movement Valhalla", suburb:"Valhalla", state:"NY", country:"US", lat:41.0715, lng:-73.7712, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Mustangs Bouldering", suburb:"Kingston", state:"NY", country:"US", lat:41.9270, lng:-74.0018, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"RockSport", suburb:"Queensbury", state:"NY", country:"US", lat:43.3600, lng:-73.6850, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Rocventures", suburb:"Rochester", state:"NY", country:"US", lat:43.1620, lng:-77.6020, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Steep Rock West", suburb:"Manhattan", state:"NY", country:"US", lat:40.8150, lng:-73.9600, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Sunrise Bouldering", suburb:"Geneseo", state:"NY", country:"US", lat:42.7959, lng:-77.8166, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Table Rock Bouldering", suburb:"Oneonta", state:"NY", country:"US", lat:42.4529, lng:-75.0638, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Crux – Champlain Valley Climbing Center", suburb:"Willsboro", state:"NY", country:"US", lat:44.3559, lng:-73.3868, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Edge Halfmoon", suburb:"Halfmoon", state:"NY", country:"US", lat:42.8515, lng:-73.7365, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Gravity Vault – Melville", suburb:"Melville", state:"NY", country:"US", lat:40.7935, lng:-73.4148, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Gravity Vault – Poughkeepsie", suburb:"Poughkeepsie", state:"NY", country:"US", lat:41.7004, lng:-73.9209, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Pad Binghamton", suburb:"Binghamton", state:"NY", country:"US", lat:42.0987, lng:-75.9180, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Rock Club", suburb:"New Rochelle", state:"NY", country:"US", lat:40.9115, lng:-73.7823, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Rock Health and Fitness", suburb:"Astoria, Queens", state:"NY", country:"US", lat:40.7644, lng:-73.9235, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Wall at Palisades", suburb:"West Nyack", state:"NY", country:"US", lat:41.0956, lng:-73.9668, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"VITAL Climbing Gym – Brooklyn", suburb:"Brooklyn", state:"NY", country:"US", lat:40.7220, lng:-73.9570, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"VITAL Climbing Gym – LES", suburb:"Manhattan", state:"NY", country:"US", lat:40.7180, lng:-73.9860, types:[IB], notes:"Lower East Side. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"VITAL Manhattan – Upper East", suburb:"Manhattan", state:"NY", country:"US", lat:40.7735, lng:-73.9565, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Niagara Climbing Center", suburb:"North Tonawanda", state:"NY", country:"US", lat:43.0387, lng:-78.8642, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Refuge Climbing & Fitness", suburb:"Las Vegas", state:"NV", country:"US", lat:36.1055, lng:-115.1919, types:[IB], notes:"Unverified this pass — flag if the type mix is off."},
    {name:"BaseCamp at CommRow", suburb:"Reno", state:"NV", country:"US", lat:39.5296, lng:-119.8138, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Mesa Rim Climbing & Fitness", suburb:"Reno", state:"NV", country:"US", lat:39.5150, lng:-119.7950, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Nevada Climbing Center", suburb:"Las Vegas", state:"NV", country:"US", lat:36.0850, lng:-115.1050, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"North Peak", suburb:"Reno", state:"NV", country:"US", lat:39.5450, lng:-119.7900, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Red Rock Climbing Center", suburb:"Las Vegas", state:"NV", country:"US", lat:36.1450, lng:-115.2600, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Block", suburb:"Reno", state:"NV", country:"US", lat:39.5350, lng:-119.8000, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Active Climbing", suburb:"Athens", state:"GA", country:"US", lat:33.9519, lng:-83.3576, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Active Climbing – Augusta", suburb:"Grovetown", state:"GA", country:"US", lat:33.4479, lng:-82.2018, types:[IB], notes:"A different location from the Athens gym above. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Adrenaline Climbing", suburb:"Suwanee", state:"GA", country:"US", lat:34.0518, lng:-84.0716, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Brunswick Rocks", suburb:"Brunswick", state:"GA", country:"US", lat:31.1500, lng:-81.4915, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Atlanta", suburb:"Atlanta", state:"GA", country:"US", lat:33.7350, lng:-84.3700, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Atlanta Bouldering", suburb:"Atlanta", state:"GA", country:"US", lat:33.7650, lng:-84.4000, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Kennesaw", suburb:"Kennesaw", state:"GA", country:"US", lat:34.0180, lng:-84.6100, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Midtown", suburb:"Atlanta", state:"GA", country:"US", lat:33.7830, lng:-84.3860, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Escalade Rock Climbing Gym", suburb:"Kennesaw", state:"GA", country:"US", lat:34.0280, lng:-84.6200, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Escalade Rock Climbing – Peachtree City", suburb:"Peachtree City", state:"GA", country:"US", lat:33.3968, lng:-84.5963, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Macon Rocks Climbing Gym", suburb:"Macon", state:"GA", country:"US", lat:32.8407, lng:-83.6324, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Savannah Climbing CoOp", suburb:"Savannah", state:"GA", country:"US", lat:32.0809, lng:-81.0912, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Stone Summit Kennesaw", suburb:"Kennesaw", state:"GA", country:"US", lat:34.0100, lng:-84.6050, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Climb'n Shop", suburb:"Carrollton", state:"GA", country:"US", lat:33.5801, lng:-85.0766, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Overlook Boulder + Fitness", suburb:"Atlanta", state:"GA", country:"US", lat:33.7150, lng:-84.4200, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Treadstone Columbus", suburb:"Columbus", state:"GA", country:"US", lat:32.4610, lng:-84.9877, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Wall Crawler Rock Club", suburb:"Atlanta", state:"GA", country:"US", lat:33.7650, lng:-84.3500, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Climb Moab", suburb:"Moab", state:"UT", country:"US", lat:38.5733, lng:-109.5498, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Contact Climbing", suburb:"St. George", state:"UT", country:"US", lat:37.0965, lng:-113.5684, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Double-Diamond Climbing Wall", suburb:"Park City", state:"UT", country:"US", lat:40.6461, lng:-111.4980, types:[IB,TR], notes:"Black Diamond Equipment's gym. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Elevation Rock Gym", suburb:"North Logan", state:"UT", country:"US", lat:41.7802, lng:-111.8105, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Fit Stop Rock Climbing Gym", suburb:"Heber", state:"UT", country:"US", lat:40.5069, lng:-111.4133, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"iROCK Utah", suburb:"Ogden", state:"UT", country:"US", lat:41.2230, lng:-111.9738, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Iron Cliffs", suburb:"Cedar City", state:"UT", country:"US", lat:37.6775, lng:-113.0619, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Momentum Fort Union", suburb:"Salt Lake City", state:"UT", country:"US", lat:40.6300, lng:-111.8400, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Momentum Indoor Climbing Gym", suburb:"Sandy", state:"UT", country:"US", lat:40.5649, lng:-111.8389, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Momentum Lehi", suburb:"Lehi", state:"UT", country:"US", lat:40.3916, lng:-111.8508, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Momentum Millcreek", suburb:"Millcreek", state:"UT", country:"US", lat:40.6864, lng:-111.8380, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Salt Lake Bouldering Project", suburb:"Salt Lake City", state:"UT", country:"US", lat:40.7450, lng:-111.9050, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Front Climbing Club", suburb:"Salt Lake City", state:"UT", country:"US", lat:40.7350, lng:-111.9000, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Front Climbing Club – Ogden", suburb:"Ogden", state:"UT", country:"US", lat:41.2200, lng:-111.9700, types:[IB,TR], notes:"A different Front Climbing Club location from the Salt Lake City one above. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Front Climbing Club – South Main", suburb:"Salt Lake City", state:"UT", country:"US", lat:40.7100, lng:-111.8950, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Quarry", suburb:"Provo", state:"UT", country:"US", lat:40.2338, lng:-111.6585, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Scratch Pad", suburb:"Bountiful", state:"UT", country:"US", lat:40.8893, lng:-111.8808, types:[IB], notes:"Combined dry-tooling and rock climbing gym. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Birmingham Boulders", suburb:"Birmingham", state:"AL", country:"US", lat:33.5250, lng:-86.8000, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Crux Climbing", suburb:"Northport", state:"AL", country:"US", lat:33.2290, lng:-87.5772, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"First Avenue Rocks", suburb:"Birmingham", state:"AL", country:"US", lat:33.5100, lng:-86.7950, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Gadrock", suburb:"Gadsden", state:"AL", country:"US", lat:34.0143, lng:-86.0066, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"High Point Climbing – Birmingham", suburb:"Birmingham", state:"AL", country:"US", lat:33.4650, lng:-86.7300, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"High Point Climbing – Huntsville", suburb:"Huntsville", state:"AL", country:"US", lat:34.7304, lng:-86.5861, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"High Point Climbing and Fitness – Lincoln Mill", suburb:"Huntsville", state:"AL", country:"US", lat:34.7500, lng:-86.6100, types:[IB,TR], notes:"A different High Point location from the one above. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"504 Climb", suburb:"Springfield", state:"TN", country:"US", lat:36.5142, lng:-86.8858, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Appalachian Bouldering Center", suburb:"Bristol", state:"TN", country:"US", lat:36.5951, lng:-82.1887, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Climb Kraft", suburb:"Nashville", state:"TN", country:"US", lat:36.1200, lng:-86.7850, types:[IB], notes:"Climb Nashville's newest bouldering-only location. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Climb Murfreesboro", suburb:"Murfreesboro", state:"TN", country:"US", lat:35.8456, lng:-86.3903, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Climb Nashville – West", suburb:"Nashville", state:"TN", country:"US", lat:36.1450, lng:-86.8300, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Climb Nashville East", suburb:"Nashville", state:"TN", country:"US", lat:36.1750, lng:-86.7300, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"High Point Climbing & Fitness – Cleveland", suburb:"Cleveland", state:"TN", country:"US", lat:35.1595, lng:-84.8766, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"High Point Climbing and Fitness", suburb:"Chattanooga", state:"TN", country:"US", lat:35.0450, lng:-85.3100, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"High Point Climbing and Fitness – Memphis", suburb:"Memphis", state:"TN", country:"US", lat:35.1300, lng:-89.9600, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"High Point Climbing and Fitness – Riverside", suburb:"Chattanooga", state:"TN", country:"US", lat:35.0700, lng:-85.2800, types:[IB,TR], notes:"A different High Point location from the one above. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Memphis Rox", suburb:"Memphis", state:"TN", country:"US", lat:35.0900, lng:-90.0450, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Onsight Rock Gym", suburb:"Knoxville", state:"TN", country:"US", lat:35.9700, lng:-83.9600, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"River Sport Climbing Center", suburb:"Knoxville", state:"TN", country:"US", lat:35.9450, lng:-83.9900, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Synergy Climbing and Ninja", suburb:"Chattanooga", state:"TN", country:"US", lat:35.0500, lng:-85.3200, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Ascent", suburb:"Murfreesboro", state:"TN", country:"US", lat:35.8500, lng:-86.4100, types:[IB], notes:"A different gym from Climb Murfreesboro, also in this city. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Crag – Franklin", suburb:"Franklin", state:"TN", country:"US", lat:35.9300, lng:-86.8500, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Crag at Cool Springs", suburb:"Franklin", state:"TN", country:"US", lat:35.9150, lng:-86.8100, types:[IB,TR], notes:"A different location from The Crag – Franklin, above. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The Crag – South Nashville", suburb:"Nashville", state:"TN", country:"US", lat:36.1000, lng:-86.7500, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Carabiner's Climbing Wall", suburb:"New Bedford", state:"MA", country:"US", lat:41.6362, lng:-70.9342, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Watertown", suburb:"Watertown", state:"MA", country:"US", lat:42.3709, lng:-71.1828, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Hadley", suburb:"Hadley", state:"MA", country:"US", lat:42.3223, lng:-72.5773, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Worcester", suburb:"Worcester", state:"MA", country:"US", lat:42.2626, lng:-71.8023, types:[IB,TR], notes:"The chain's original flagship location. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Framingham", suburb:"Framingham", state:"MA", country:"US", lat:42.2793, lng:-71.4162, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Cambridge (Smith Place)", suburb:"Cambridge", state:"MA", country:"US", lat:42.3900, lng:-71.1300, types:[IB,TR], notes:"One of three distinct Central Rock Gym locations in Cambridge. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Arsenal Yards", suburb:"Watertown", state:"MA", country:"US", lat:42.3650, lng:-71.1750, types:[IB,TR], notes:"A different Watertown location from the one above. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Boston", suburb:"Boston", state:"MA", country:"US", lat:42.3550, lng:-71.0600, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Cambridge (Alewife)", suburb:"Cambridge", state:"MA", country:"US", lat:42.3960, lng:-71.1440, types:[IB,TR], notes:"A different Cambridge location from the Smith Place one above. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Fenway", suburb:"Boston", state:"MA", country:"US", lat:42.3450, lng:-71.0950, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Harvard Square", suburb:"Cambridge", state:"MA", country:"US", lat:42.3730, lng:-71.1190, types:[IB,TR], notes:"A third distinct Cambridge location. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Randolph", suburb:"Randolph", state:"MA", country:"US", lat:42.1668, lng:-71.0413, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Stoneham", suburb:"Stoneham", state:"MA", country:"US", lat:42.4792, lng:-71.0967, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Central Rock Gym – Waltham", suburb:"Waltham", state:"MA", country:"US", lat:42.3765, lng:-71.2356, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"MetroRock Boston", suburb:"Boston", state:"MA", country:"US", lat:42.3400, lng:-71.0700, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"MetroRock Littleton", suburb:"Littleton", state:"MA", country:"US", lat:42.5334, lng:-71.4912, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"MetroRock Newburyport", suburb:"Newburyport", state:"MA", country:"US", lat:42.8126, lng:-70.8676, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Rock Spot Climbing", suburb:"Boston", state:"MA", country:"US", lat:42.2650, lng:-71.1250, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Rock Spot Climbing – South Boston", suburb:"Boston", state:"MA", country:"US", lat:42.3350, lng:-71.0400, types:[IB,TR], notes:"A different Rock Spot location from the one above. Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Rock Spot Climbing – Brookline", suburb:"Brookline", state:"MA", country:"US", lat:42.3467, lng:-71.1206, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Rock Spot Climbing – Malden", suburb:"Malden", state:"MA", country:"US", lat:42.4251, lng:-71.0662, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"The El Dojo", suburb:"Northampton", state:"MA", country:"US", lat:42.3251, lng:-72.6412, types:[IB], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."},
    {name:"Willy's World Adventure", suburb:"Eastham", state:"MA", country:"US", lat:41.8306, lng:-69.9709, types:[IB,TR], notes:"Sourced from Mountain Project's gym directory — city-level position, not an exact address."}
  ].map((g,i)=>({...g, id:'seed-'+i, community:false, country: g.country || 'AU'}));
