// Regional research: the step BEFORE an import batch. One geographic section (a country, some of its states, or a bounding box
// inside one country) is researched into candidates with evidence, reconciled against Bouldeer, reviewed by a human, and only the
// accepted candidates are staged as an ordinary insert batch under import/batches/. See docs/import-workflow.md ("Regional research").
//
//   import/research/<YYYY-MM-DD-slug>/
//     section.json       scope + description (written by `research new`)
//     sources.json       source registry {S1: {kind, title, url, language, accessed}}
//     candidates.ndjson  one candidate per line (the research output)
//     reconcile.json/.md generated by `research reconcile` (deterministic; bound to the input hashes and the index)
//     review.json        the human decision for EVERY candidate
//
// Offline and read-only towards production: no network, no credentials, no write gate. Duplicate detection is the importer's own
// planBatch/match.js (thresholds and classification unchanged), plus review flags that are only ever STRICTER: they can send a
// candidate to review, never clear one. The staged batch then goes through validate/plan/import exactly like any other batch, and
// importer.js re-checks this provenance (verifyStagedBatch) before it will even plan it.
'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const N = require('./normalize');
const V = require('./validate');
const M = require('./match');
const P = require('./plan');
const { canonicalSha } = require('./stage');

const SCHEMA_VERSION = 1;
const MAX_STAGED = 1000;   // = importer.js MAX_ROWS (one atomic insert); tests/import-research.test.js keeps them equal
const FILES = Object.freeze({ section: 'section.json', sources: 'sources.json', candidates: 'candidates.ndjson', reconcile: 'reconcile.json', report: 'reconcile.md', review: 'review.json' });
const researchDir = root => path.join(root, 'import', 'research');

// Review flags. STRICTER than, and in addition to, the importer's match.js (which is unchanged and still decides existing/probable).
const R = Object.freeze({
  NEARBY_ANY_M: 150,        // any gym within 150 m, whatever its name (importer: 60 m)
  RELATED_NAME_M: 15000,    // related name (chain branch, rebrand, translation in an alias) up to 15 km (importer: 100 m)
  OTHER_COUNTRY_M: 2000,    // a gym of ANOTHER country within 2 km (wrong country code; the importer only compares within a country)
});
if (R.NEARBY_ANY_M < M.T.PROBABLE_COLOCATED_M || R.RELATED_NAME_M < M.T.PROBABLE_RENAMED_M) throw new Error('research review radii must not be looser than match.js');

const CANDIDATE_KEYS = ['cid', 'name', 'name_local', 'aliases', 'chain', 'country', 'state', 'suburb', 'address', 'lat', 'lng', 'coord_source', 'coord_precision',
  'types', 'website', 'category', 'status_claim', 'bouldering', 'evidence', 'research_notes', 'notes', 'photo'];
const REQUIRED = ['cid', 'name', 'country', 'state', 'suburb', 'lat', 'lng', 'coord_source', 'coord_precision', 'types', 'category', 'status_claim', 'bouldering', 'evidence'];
const CID = /^[a-z0-9][a-z0-9-]{1,59}$/;
const RESERVED_CID = /^(seed-|community-|g-)/;   // could be confused with a production id in reviewed_against
const SOURCE_ID = /^[A-Za-z0-9_-]{1,40}$/;
const PRIMARY_KINDS = new Set(['official-site', 'official-social', 'chain-store-list']);
const SOURCE_KINDS = new Set([...PRIMARY_KINDS, 'federation', 'directory', 'map-data', 'news', 'other']);
const SUPPORTS = new Set(['exists', 'open', 'name', 'address', 'location', 'bouldering', 'ropes', 'closed', 'relocated', 'chain']);
const CATEGORIES = new Set(['commercial-gym', 'university', 'club', 'outdoor-area', 'shop', 'other']);
const STATUSES = new Set(['open', 'closed', 'opening-soon', 'temporary', 'unknown']);
const BOULDERING = new Set(['yes', 'no', 'unknown']);
const PRECISIONS = new Set(['entrance', 'building', 'street', 'area']);
const COORD_METHODS = new Set(['osm', 'official-map', 'chain-store-list', 'geocoded-address', 'map-service-pin']);
const DECISIONS = new Set(['accept', 'same-as', 'reject', 'defer']);
const REJECT_CODES = new Set(['duplicate', 'closed', 'temporary', 'outdoor-area', 'no-bouldering', 'not-a-gym', 'insufficient-evidence', 'out-of-scope']);
const DUP_FLAGS = new Set(['importer-probable-duplicate', 'alias-match', 'name-match', 'related-name-nearby', 'nearby-gym', 'other-country-nearby', 'same-website', 'other-section']);
// A blocker means "cannot be accepted"; the suggestion is what the reviewer most likely records instead.
const SUGGEST = { 'out-of-scope': 'reject out-of-scope', 'outdoor-area': 'reject outdoor-area', 'not-a-gym': 'reject not-a-gym', closed: 'reject closed', temporary: 'reject temporary', 'no-bouldering': 'reject no-bouldering' };

const DATE = /^\d{4}-\d{2}-\d{2}$/;
const isDate = s => typeof s === 'string' && DATE.test(s) && !Number.isNaN(Date.parse(s + 'T00:00:00Z')) && new Date(s + 'T00:00:00Z').toISOString().slice(0, 10) === s;
const isStr = v => typeof v === 'string' && v.trim().length > 0;
function isHttpUrl(s) {
  if (typeof s !== 'string' || s !== s.trim()) return false;
  try { const u = new URL(s); return (u.protocol === 'https:' || u.protocol === 'http:') && !u.username && !u.password; } catch (e) { return false; }
}
const sha256 = s => crypto.createHash('sha256').update(s).digest('hex');
const byStr = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

// ---- files and hashes (canonical, so a line-ending conversion can never change a hash) ---------------------------------
const readJson = file => JSON.parse(fs.readFileSync(file, 'utf8'));
const jsonSha = file => canonicalSha(readJson(file));
const ndjsonLines = text => text.split('\n').map(l => l.replace(/\r$/, '')).filter(l => l.trim());
const ndjsonSha = file => sha256(ndjsonLines(fs.readFileSync(file, 'utf8')).join('\n'));
const sectionPath = (root, arg) => { const p = fs.existsSync(arg) ? path.resolve(arg) : path.join(researchDir(root), arg); if (!fs.existsSync(p) || !fs.statSync(p).isDirectory()) throw new Error('research section not found: ' + arg); return p; };

function loadSection(dir) {
  const id = path.basename(dir), problems = [];
  const need = k => { const f = path.join(dir, FILES[k]); if (!fs.existsSync(f)) { problems.push(`${FILES[k]} is missing`); return null; } return f; };
  let section = null, sources = null;
  const sf = need('section'), rf = need('sources'), cf = need('candidates');
  try { if (sf) section = readJson(sf); } catch (e) { problems.push('section.json is not valid JSON'); }
  try { if (rf) sources = readJson(rf); } catch (e) { problems.push('sources.json is not valid JSON'); }
  const lines = cf ? ndjsonLines(fs.readFileSync(cf, 'utf8')).map((text, i) => { try { return { line: i + 1, rec: JSON.parse(text) }; } catch (e) { return { line: i + 1, parseError: e.message }; } }) : [];
  return { id, dir, section, sources, lines, problems };
}

async function checkSection(s) {
  const d = await V.deps(), out = [], sec = s.section;
  if (!P.BATCH_DIR_RE.test(s.id)) out.push(`section directory "${s.id}" must look like YYYY-MM-DD-short-slug (it becomes the batch id)`);
  if (!sec || typeof sec !== 'object') return out.concat(s.problems);
  if (sec.schema_version !== SCHEMA_VERSION) out.push('section.json schema_version must be 1');
  if (sec.section_id !== s.id) out.push(`section.json section_id (${sec.section_id}) does not match the directory name`);
  if (!isStr(sec.title) || !isStr(sec.description) || sec.description.length < 10) out.push('section.json needs a title and a description (>= 10 chars)');
  if (!isDate(sec.created)) out.push('section.json created must be YYYY-MM-DD');
  const sc = sec.scope || {};
  if (!/^[A-Z]{2}$/.test(sc.country || '') || !d.STATES[sc.country]) out.push(`scope.country must be a country the app supports (js/modules/regions.js); got ${JSON.stringify(sc.country)}`);
  else if (sc.states !== null && sc.states !== undefined) {
    if (!Array.isArray(sc.states) || !sc.states.length) out.push('scope.states must be null (whole country) or a non-empty list of region codes');
    else sc.states.filter(st => !d.STATES[sc.country].some(([c]) => c === st)).forEach(st => out.push(`scope.states: "${st}" is not a ${sc.country} region code`));
  }
  if (sc.bbox !== null && sc.bbox !== undefined) {
    const b = sc.bbox;
    if (!Array.isArray(b) || b.length !== 4 || !b.every(Number.isFinite) || b[0] >= b[2] || b[1] >= b[3] || Math.abs(b[0]) > 180 || Math.abs(b[2]) > 180 || Math.abs(b[1]) > 90 || Math.abs(b[3]) > 90) out.push('scope.bbox must be null or [west, south, east, north] with west < east and south < north');
  }
  return out.concat(s.problems);
}

function checkSources(src) {
  const out = [];
  if (!src || src.schema_version !== SCHEMA_VERSION || !src.sources || typeof src.sources !== 'object' || Array.isArray(src.sources)) return ['sources.json must be {"schema_version":1,"sources":{...}}'];
  for (const [id, s] of Object.entries(src.sources)) {
    if (!SOURCE_ID.test(id)) out.push(`source id "${id}" must be letters/digits/_/- (e.g. S1)`);
    if (!s || typeof s !== 'object') { out.push(`source ${id} must be an object`); continue; }
    if (!SOURCE_KINDS.has(s.kind)) out.push(`source ${id}: kind must be one of ${[...SOURCE_KINDS].join(', ')}`);
    if (!isStr(s.title)) out.push(`source ${id}: title is required`);
    if (!isHttpUrl(s.url)) out.push(`source ${id}: url must be a plain http(s) URL`);
    if (!isDate(s.accessed)) out.push(`source ${id}: accessed must be YYYY-MM-DD`);
    if (s.language !== undefined && !/^[a-z]{2,3}(-[A-Za-z0-9]{2,8})?$/.test(s.language)) out.push(`source ${id}: language must be a language tag like "en" or "ja"`);
  }
  return out;
}

// The importer record a candidate becomes (fixed key order; `source` links the imported gym back to this section and candidate).
const toImportRecord = (c, sectionId) => ({
  name: c.name, suburb: c.suburb, state: c.state, country: c.country, lat: c.lat, lng: c.lng, types: c.types,
  address: c.address == null || c.address === '' ? null : c.address, notes: c.notes == null || c.notes === '' ? null : c.notes,
  photo: c.photo == null || c.photo === '' ? null : c.photo, source: `research:${sectionId}#${c.cid}`,
});
const SOURCE_REF = /^research:(\d{4}-\d{2}-\d{2}-[a-z0-9][a-z0-9-]{1,60})#([a-z0-9][a-z0-9-]{1,59})$/;

// Validate one candidate. errors = must be fixed; blockers = cannot be accepted; flags = a human must look (accept needs a reason).
async function checkCandidate(c, { section, sources, sectionId }) {
  const errors = [], blockers = [], flags = [];
  const err = (code, detail) => errors.push({ code, detail }), block = (code, detail) => blockers.push({ code, detail }), flag = (code, detail, ids) => flags.push({ code, detail, ...(ids ? { ids } : {}) });
  if (!c || typeof c !== 'object' || Array.isArray(c)) { err('bad-record', 'line must be a JSON object'); return { errors, blockers, flags }; }
  Object.keys(c).filter(k => !CANDIDATE_KEYS.includes(k)).forEach(k => err('unknown-field', `unknown field "${k}"`));
  REQUIRED.filter(k => c[k] === undefined || c[k] === null || c[k] === '').forEach(k => err('required', `${k} is required`));
  if (c.cid !== undefined && (typeof c.cid !== 'string' || !CID.test(c.cid) || RESERVED_CID.test(c.cid))) err('bad-cid', 'cid must be lower-case letters/digits/hyphens (2-60) and must not start with seed-, community- or g-');
  for (const k of ['name_local', 'chain', 'research_notes']) if (c[k] != null && !isStr(c[k])) err('bad-text', `${k} must be text or null`);
  if (c.aliases != null && (!Array.isArray(c.aliases) || c.aliases.some(a => !isStr(a)))) err('bad-aliases', 'aliases must be a list of names');
  if (c.website != null && !isHttpUrl(c.website)) err('bad-url', 'website must be a plain http(s) URL or null');
  if (c.category !== undefined && !CATEGORIES.has(c.category)) err('bad-enum', `category must be one of ${[...CATEGORIES].join(', ')}`);
  if (c.status_claim !== undefined && !STATUSES.has(c.status_claim)) err('bad-enum', `status_claim must be one of ${[...STATUSES].join(', ')}`);
  if (c.bouldering !== undefined && !BOULDERING.has(c.bouldering)) err('bad-enum', 'bouldering must be yes, no or unknown');
  if (c.coord_precision !== undefined && !PRECISIONS.has(c.coord_precision)) err('bad-enum', `coord_precision must be one of ${[...PRECISIONS].join(', ')}`);
  const known = (sources && sources.sources) || {};
  const cs = c.coord_source;
  if (cs !== undefined && (!cs || typeof cs !== 'object' || !known[cs.source] || !COORD_METHODS.has(cs.method) || (cs.ref != null && !isStr(cs.ref)))) err('bad-coord-source', `coord_source must be {source: a sources.json id, method: ${[...COORD_METHODS].join('|')}, ref?: text}; coordinates are never invented`);
  const ev = Array.isArray(c.evidence) ? c.evidence : null;
  if (c.evidence !== undefined && (!ev || !ev.length)) err('bad-evidence', 'evidence must be a non-empty list');
  (ev || []).forEach((e, i) => {
    if (!e || typeof e !== 'object' || !known[e.source]) return err('bad-evidence', `evidence[${i}].source must be a sources.json id`);
    if (!isHttpUrl(e.url)) err('bad-evidence', `evidence[${i}].url must be a plain http(s) URL`);
    if (!isDate(e.accessed)) err('bad-evidence', `evidence[${i}].accessed must be YYYY-MM-DD`);
    if (!Array.isArray(e.supports) || !e.supports.length || e.supports.some(s => !SUPPORTS.has(s))) err('bad-evidence', `evidence[${i}].supports must list what it confirms: ${[...SUPPORTS].join(', ')}`);
  });
  if (Array.isArray(c.types) && c.types.includes('indoor-bouldering') !== (c.bouldering === 'yes') && BOULDERING.has(c.bouldering)) err('types-vs-bouldering', `types ${c.types.includes('indoor-bouldering') ? 'include' : 'lack'} indoor-bouldering but bouldering is "${c.bouldering}"`);
  // the importer's own record validation (same code the importer runs). One exception: a candidate whose bouldering is "unknown" or
  // "no" may have an EMPTY types list instead of an unconfirmed placeholder. Such a candidate is always blocked (never accepted or
  // staged); an accepted candidate has bouldering "yes", so types include "indoor-bouldering" and pass the importer's own check.
  const noTypesAllowed = Array.isArray(c.types) && c.types.length === 0 && (c.bouldering === 'unknown' || c.bouldering === 'no');
  const v = await V.validateNewRecord(toImportRecord(c, sectionId));
  v.errors.filter(e => !(noTypesAllowed && e.code === 'bad-types' && e.field === 'types')).forEach(e => err('record-' + e.code, e.message));   // its warnings come back from the importer's plan (reconcile)
  if (errors.length) return { errors, blockers, flags };

  // ---- scope and category -------------------------------------------------------------------------------------------
  const sc = section.scope;
  if (c.country !== sc.country) block('out-of-scope', `country ${c.country} is outside this section (${sc.country})`);
  else if (Array.isArray(sc.states) && !sc.states.includes(c.state)) block('out-of-scope', `state ${c.state} is outside this section (${sc.states.join(', ')})`);
  if (Array.isArray(sc.bbox) && !(c.lng >= sc.bbox[0] && c.lng <= sc.bbox[2] && c.lat >= sc.bbox[1] && c.lat <= sc.bbox[3])) block('out-of-scope', 'the pin is outside the section bbox');
  if (c.category === 'outdoor-area') block('outdoor-area', 'outdoor climbing areas are not gyms');
  else if (c.category === 'shop' || c.category === 'other') block('not-a-gym', `category ${c.category}`);
  else if (c.category !== 'commercial-gym') flag('limited-access', `${c.category} wall: check it is open to the public`);
  if (c.status_claim !== 'open') block(c.status_claim === 'closed' ? 'closed' : c.status_claim === 'temporary' ? 'temporary' : 'status-not-open', `status_claim is ${c.status_claim}`);
  // ---- evidence ------------------------------------------------------------------------------------------------------
  const primary = ev.filter(e => PRIMARY_KINDS.has(known[e.source].kind));
  const says = (list, what) => list.some(e => e.supports.includes(what));
  if (!says(primary, 'exists') || !says(primary, 'open')) block('insufficient-evidence', 'needs a primary source (official site/social, chain store list) confirming it exists and is open; a directory or search result alone is not enough');
  if (c.bouldering === 'no') block('no-bouldering', 'confirmed rope-only (new additions need a bouldering offering)');
  else if (c.bouldering === 'unknown') block('bouldering-unknown', 'bouldering offering not established (never assumed)');
  else if (!says(primary, 'bouldering')) block('no-bouldering-evidence', 'bouldering is "yes" but no primary source confirms it');
  if (c.coord_precision === 'area') block('coarse-coordinates', 'coordinates only locate the area, not the gym');
  else if (c.coord_precision === 'street') flag('weak-coordinates', 'coordinates are street-level, not the building');
  if (new Set(ev.map(e => e.source)).size < 2) flag('single-source', 'all evidence comes from one source');
  return { errors, blockers, flags };
}

// ---- stricter review comparisons -----------------------------------------------------------------------------------------
const namesOf = c => [c.name, c.name_local, ...(c.aliases || [])].filter(isStr);
function reviewPair(a, b) {   // a, b: {names, country, lat, lng, address, suburb, state}; same country
  const d = N.meters(a, b), dist_m = Math.round(d);
  for (const [i, na] of a.names.entries()) for (const [j, nb] of b.names.entries()) {
    const p = M.evaluatePair({ ...a, name: na }, { ...b, name: nb });
    if (p) return { code: i || j ? 'alias-match' : 'name-match', detail: `${p.reason} ("${na}" / "${nb}", ${dist_m} m)`, dist_m };
    if (d <= R.RELATED_NAME_M && N.namesRelated(na, nb)) return { code: 'related-name-nearby', detail: `related names "${na}" / "${nb}" ${dist_m} m apart`, dist_m };
  }
  if (d <= R.NEARBY_ANY_M) return { code: 'nearby-gym', detail: `${dist_m} m apart`, dist_m };
  return null;
}
const siteKey = u => { try { const x = new URL(u); return x.hostname.replace(/^www\./, '').toLowerCase() + x.pathname.replace(/\/+$/, '').toLowerCase(); } catch (e) { return null; } };

// Other research sections of the SAME country (by their section.json scope). Only those are compared with, and only those are bound
// into reconcile.json's inputs, so an unrelated country's section changing never makes this reconcile stale. A section whose
// section.json cannot be read is included (conservative). A candidate filed under a different country's section is out of scope
// there (blocked, never stageable); the importer's own plan still compares every staged batch by record country at staging time.
const sectionCountry = sdir => { try { return JSON.parse(fs.readFileSync(path.join(sdir, FILES.section), 'utf8')).scope.country || null; } catch (e) { return null; } };
function otherSections(root, exceptId, country) {
  const dir = researchDir(root), out = [], seen = [];
  if (!fs.existsSync(dir)) return { out, seen };
  for (const name of fs.readdirSync(dir).sort()) {
    const f = path.join(dir, name, FILES.candidates);
    if (name === exceptId || !fs.existsSync(f)) continue;
    const sc = sectionCountry(path.join(dir, name));
    if (sc && sc !== country) continue;
    seen.push({ id: name, candidates_sha256: ndjsonSha(f) });
    for (const text of ndjsonLines(fs.readFileSync(f, 'utf8'))) {
      let c; try { c = JSON.parse(text); } catch (e) { continue; }
      if (c && c.country === country && isStr(c.cid) && isStr(c.name) && Number.isFinite(c.lat) && Number.isFinite(c.lng)) out.push({ ...c, ref: `${name}#${c.cid}`, names: namesOf(c) });
    }
  }
  return { out, seen };
}

// Plan records with the importer's own planner in a scratch batch named like the section (so the staged batch, once it exists, is
// excluded from "other staged batches" exactly as the importer excludes a batch from itself).
async function probePlan({ sectionId, records, index, root, decisions = null }) {
  const scratch = fs.mkdtempSync(path.join(os.tmpdir(), 'gym-research-'));
  try {
    const dir = path.join(scratch, sectionId);
    fs.mkdirSync(dir);
    fs.writeFileSync(path.join(dir, 'batch.json'), JSON.stringify({ schema_version: 1, batch_id: sectionId, description: 'research probe' }));
    fs.writeFileSync(path.join(dir, 'records.ndjson'), records.map(r => JSON.stringify(r)).join('\n') + '\n');
    if (decisions) fs.writeFileSync(path.join(dir, 'decisions.json'), JSON.stringify({ decisions }));
    return await P.planBatch({ dir, index, batchesDir: path.join(root, 'import', 'batches'), includeStaged: true });
  } finally { fs.rmSync(scratch, { recursive: true, force: true }); }
}

// ---- reconcile ----------------------------------------------------------------------------------------------------------
async function reconcile(dir, { index, root }) {
  const s = loadSection(dir);
  const problems = (await checkSection(s)).concat(s.sources ? checkSources(s.sources) : []);
  if (problems.length) { const e = new Error('research section is not valid:\n  - ' + problems.join('\n  - ')); e.problems = problems; throw e; }
  if (!index.metaMatches) throw new Error('the match index does not match index-meta.json; rebuild it (build-index --live) before reconciling');
  const ctx = { section: s.section, sources: s.sources, sectionId: s.id };
  const items = [];
  for (const { line, rec, parseError } of s.lines) {
    const it = { line, c: rec, cid: rec && typeof rec.cid === 'string' ? rec.cid : `line-${line}` };
    if (parseError) Object.assign(it, { errors: [{ code: 'bad-json', detail: parseError }], blockers: [], flags: [] });
    else Object.assign(it, await checkCandidate(rec, ctx));
    items.push(it);
  }
  const cidCount = new Map(); items.forEach(it => cidCount.set(it.cid, (cidCount.get(it.cid) || 0) + 1));
  items.filter(it => cidCount.get(it.cid) > 1).forEach(it => it.errors.push({ code: 'duplicate-cid', detail: `cid ${it.cid} is used by more than one line` }));
  const valid = items.filter(it => !it.errors.length).sort((a, b) => byStr(a.cid, b.cid));

  // 1. the importer's own classification (unchanged thresholds), all valid candidates together. The planner requires a non-empty
  //    types list; duplicate matching ignores types, so a candidate allowed an empty list (bouldering unknown/no: always blocked,
  //    never staged) is probed with a stand-in. The stand-in exists only in this in-memory probe and is never written anywhere.
  const probeRecord = c => { const r = toImportRecord(c, s.id); return r.types.length ? r : { ...r, types: ['top-rope'] }; };
  const plan = valid.length ? await probePlan({ sectionId: s.id, records: valid.map(it => probeRecord(it.c)), index, root }) : { records: [], staged_batches_compared: [] };
  const cidById = new Map();
  valid.forEach((it, i) => { it.imp = plan.records[i]; if (it.imp.id) cidById.set(it.imp.id, it.cid); });
  for (const it of valid) {
    const r = it.imp;
    if (r.class === 'invalid') (r.errors || []).forEach(e => it.errors.push({ code: 'record-' + e.code, detail: e.message }));
    (r.warnings || []).forEach(w => it.flags.push({ code: 'importer-warning', detail: `${w.code}: ${w.message}` }));
    if (r.class === 'probable-duplicate') it.flags.push({ code: 'importer-probable-duplicate', detail: r.candidates.map(x => `${x.id || '(unfrozen)'} ${x.reason} ${x.dist_m} m`).join('; '), ids: r.candidates.map(x => (x.batch === '(this batch)' ? cidById.get(x.id) : x.id)).filter(Boolean) });
  }
  // 2. stricter review flags: aliases/translations, related names up to 15 km, anything within 150 m, other countries within 2 km,
  //    the same website, and candidates of other research sections
  const country = s.section.scope.country, pool = index.byCountry.get(country) || [];
  const others = otherSections(root, s.id, country);
  const live = valid.filter(it => !it.errors.length).map(it => ({ it, g: { ...it.c, names: namesOf(it.c) } }));
  for (const { it, g } of live) {
    const add = (code, detail, id) => it.flags.push({ code, detail, ids: [id] });
    for (const e of pool) { const p = reviewPair(g, { ...e, names: [e.name] }); if (p) add(p.code, `${e.id} "${e.name}": ${p.detail}`, e.id); }
    for (const e of index.entries) if (e.country !== country && N.meters(g, e) <= R.OTHER_COUNTRY_M) add('other-country-nearby', `${e.id} "${e.name}" (${e.country}) ${Math.round(N.meters(g, e))} m away`, e.id);
    for (const o of live) {
      if (o.it === it) continue;
      const p = reviewPair(g, o.g);
      if (p) add(p.code, `candidate ${o.it.cid} "${o.g.name}": ${p.detail}`, o.it.cid);
      if (g.website && o.g.website && siteKey(g.website) && siteKey(g.website) === siteKey(o.g.website)) add('same-website', `candidate ${o.it.cid} has the same website`, o.it.cid);
    }
    for (const o of others.out) { const p = reviewPair(g, o); if (p) add('other-section', `${o.ref} "${o.name}": ${p.code} ${p.detail}`, o.ref); }
  }
  // 3. classify and suggest (the suggestion is never a decision)
  const out = items.sort((a, b) => byStr(a.cid, b.cid) || a.line - b.line).map(it => {
    const seen = new Set(), flags = (it.flags || []).filter(f => { const k = f.code + '|' + (f.ids || []).join(',') + '|' + f.detail; if (seen.has(k)) return false; seen.add(k); return true; })
      .sort((a, b) => byStr(a.code, b.code) || byStr((a.ids || []).join(), (b.ids || []).join()) || byStr(a.detail, b.detail));
    let cls, suggested;
    if (it.errors.length) { cls = 'invalid'; suggested = 'fix the candidate (or reject/defer)'; }
    else if (it.imp.class === 'existing') { cls = 'existing'; suggested = `same-as ${it.imp.match.id}`; }
    else if (it.blockers.length) { cls = 'blocked'; suggested = SUGGEST[it.blockers[0].code] || 'defer'; }
    else if (flags.length) { cls = 'review'; suggested = 'review'; }
    else { cls = 'ready'; suggested = 'accept'; }
    const o = { cid: it.cid, line: it.line, name: it.c && typeof it.c.name === 'string' ? it.c.name : null, class: cls, suggested };
    if (it.imp) o.importer = { class: it.imp.class, id: it.imp.id, ...(it.imp.match ? { match: it.imp.match } : {}) };
    if (it.errors.length) o.errors = it.errors;
    if (it.blockers.length) o.blockers = it.blockers;
    if (flags.length) o.flags = flags;
    o.review_ids = [...new Set(flags.filter(f => DUP_FLAGS.has(f.code)).flatMap(f => f.ids || []))].sort(byStr);
    return o;
  });
  const counts = { candidates: out.length, ready: 0, review: 0, blocked: 0, existing: 0, invalid: 0 };
  out.forEach(o => counts[o.class]++);
  const body = {
    schema_version: SCHEMA_VERSION, section_id: s.id,
    inputs: {
      section_sha256: jsonSha(path.join(dir, FILES.section)), sources_sha256: jsonSha(path.join(dir, FILES.sources)), candidates_sha256: ndjsonSha(path.join(dir, FILES.candidates)),
      index: { sha256: index.sha256, count: index.entries.length }, staged_batches_compared: plan.staged_batches_compared, other_sections_compared: others.seen,
    },
    review_radii_m: R, counts, candidates: out,
  };
  return { ...body, reconcile_sha256: canonicalSha(body) };
}

function renderReconcile(rc, section) {
  const L = [`# Regional research: ${section.title} (${rc.section_id})`, ''];
  const sc = section.scope;
  L.push(`Scope: ${sc.country}${Array.isArray(sc.states) ? ' / ' + sc.states.join(', ') : ' (whole country)'}${Array.isArray(sc.bbox) ? ' / bbox ' + sc.bbox.join(',') : ''}`);
  L.push(`Index: ${rc.inputs.index.count} gyms, sha256 ${rc.inputs.index.sha256.slice(0, 12)}… | staged batches compared: ${rc.inputs.staged_batches_compared.join(', ') || 'none'} | other sections compared: ${rc.inputs.other_sections_compared.map(o => o.id).join(', ') || 'none'}`);
  L.push(`Review radii (stricter than the importer): any gym ${R.NEARBY_ANY_M} m, related name ${R.RELATED_NAME_M / 1000} km, other country ${R.OTHER_COUNTRY_M / 1000} km`, '');
  const c = rc.counts;
  L.push(`## Summary`, `${c.candidates} candidate(s): ready ${c.ready} | review ${c.review} | blocked ${c.blocked} | already in Bouldeer ${c.existing} | invalid ${c.invalid}`, '');
  const sec = (title, cls, fn) => { const list = rc.candidates.filter(o => o.class === cls); if (!list.length) return; L.push(`## ${title} (${list.length})`); list.forEach(o => fn(o)); L.push(''); };
  sec('Invalid: fix candidates.ndjson', 'invalid', o => L.push(`- ${o.cid} (line ${o.line}) "${o.name || '?'}": ` + o.errors.map(e => `${e.code}: ${e.detail}`).join('; ')));
  sec('Already in Bouldeer (suggested: same-as; never inserted)', 'existing', o => L.push(`- ${o.cid} "${o.name}" -> ${o.importer.match.id} "${o.importer.match.name}" (${o.importer.match.reason}, ${o.importer.match.dist_m} m)${o.blockers ? ' | also: ' + o.blockers.map(b => b.code).join(', ') : ''}`));
  sec('Needs review (accept needs a reason and reviewed_against covering every listed id)', 'review', o => {
    L.push(`- ${o.cid} "${o.name}" [${o.importer.id}]${o.review_ids.length ? ' reviewed_against must include: ' + o.review_ids.join(', ') : ''}`);
    o.flags.forEach(f => L.push(`  - ${f.code}: ${f.detail}`));
  });
  sec('Blocked: cannot be accepted', 'blocked', o => L.push(`- ${o.cid} "${o.name}": ${o.blockers.map(b => `${b.code} (${b.detail})`).join('; ')} -> suggested: ${o.suggested}`));
  sec('Ready (no flags; still needs an explicit accept)', 'ready', o => L.push(`- ${o.cid} "${o.name}" [${o.importer.id}]`));
  L.push('## Next', 'Write review.json with one decision per candidate (docs/import-workflow.md, "Regional research"), then `node scripts/gym-import.js research stage ' + rc.section_id + '`.', 'Nothing here touches production.');
  return L.join('\n');
}

// ---- review decisions -------------------------------------------------------------------------------------------------------
function checkDecision(o, dec, { index, candidateById }) {
  const out = [], c = candidateById.get(o.cid) || {};
  if (!dec || typeof dec !== 'object' || !DECISIONS.has(dec.decision)) return [`${o.cid}: decision must be one of ${[...DECISIONS].join(', ')}`];
  const reason = typeof dec.reason === 'string' ? dec.reason.trim() : '';
  if (dec.decision === 'accept') {
    if (o.class !== 'ready' && o.class !== 'review') out.push(`${o.cid}: cannot be accepted (class ${o.class}${o.blockers ? ': ' + o.blockers.map(b => b.code).join(', ') : ''})`);
    if (o.class === 'review') {
      if (reason.length < 8) out.push(`${o.cid}: accepting a flagged candidate needs a reason (>= 8 chars)`);
      const got = new Set(Array.isArray(dec.reviewed_against) ? dec.reviewed_against : []);
      const missing = o.review_ids.filter(id => !got.has(id));
      if (missing.length) out.push(`${o.cid}: reviewed_against must include ${missing.join(', ')}`);
    }
  } else if (dec.decision === 'same-as') {
    if (!index.byId.has(dec.same_as)) out.push(`${o.cid}: same_as must be the id of a gym in Bouldeer (got ${JSON.stringify(dec.same_as)})`);
    if (dec.followup != null && dec.followup !== 'location-update') out.push(`${o.cid}: followup may only be "location-update" (a separate update batch)`);
  } else if (dec.decision === 'reject') {
    if (!REJECT_CODES.has(dec.reason_code)) out.push(`${o.cid}: reason_code must be one of ${[...REJECT_CODES].join(', ')}`);
    if (c.bouldering === 'no' && dec.reason_code !== 'no-bouldering') out.push(`${o.cid}: a confirmed rope-only candidate is rejected with reason_code "no-bouldering"`);
    if (dec.reason_code === 'no-bouldering' && c.bouldering !== 'no') out.push(`${o.cid}: "no-bouldering" needs bouldering "no" (confirmed rope-only); an unknown offering is deferred or insufficient-evidence`);
  } else if (reason.length < 8) out.push(`${o.cid}: defer needs a reason (>= 8 chars)`);
  return out;
}

function readReview(dir, rc) {
  const f = path.join(dir, FILES.review);
  if (!fs.existsSync(f)) return { problems: ['review.json is missing: every candidate needs a human decision'] };
  let rv; try { rv = readJson(f); } catch (e) { return { problems: ['review.json is not valid JSON'] }; }
  const problems = [];
  if (!rv || rv.schema_version !== SCHEMA_VERSION || rv.section_id !== rc.section_id) problems.push('review.json needs schema_version 1 and this section_id');
  if (!isStr(rv && rv.reviewer)) problems.push('review.json needs the reviewer');
  if (!isDate(rv && rv.reviewed)) problems.push('review.json reviewed must be YYYY-MM-DD');
  const decisions = rv && rv.decisions && typeof rv.decisions === 'object' && !Array.isArray(rv.decisions) ? rv.decisions : null;
  if (!decisions) problems.push('review.json needs a "decisions" object keyed by cid');
  return { rv, decisions: decisions || {}, problems };
}

// ---- stage --------------------------------------------------------------------------------------------------------------
async function stage(dir, { index, root, batchesDir = path.join(root, 'import', 'batches') }) {
  const refuse = problems => ({ action: 'refused', problems });
  const rc = await reconcile(dir, { index, root });
  const cf = path.join(dir, FILES.reconcile);
  if (!fs.existsSync(cf)) return refuse(['reconcile.json is missing: run `research reconcile` and review its report first']);
  if (canonicalSha(readJson(cf)) !== canonicalSha(rc)) return refuse(['reconcile.json is stale (the candidates, sources, index, staged batches or other sections changed): run `research reconcile` again and re-review']);
  const { rv, decisions, problems } = readReview(dir, rc);
  if (problems.length) return refuse(problems);
  const s = loadSection(dir);
  const candidateById = new Map(s.lines.filter(l => l.rec && typeof l.rec.cid === 'string').map(l => [l.rec.cid, l.rec]));
  const known = new Set(rc.candidates.map(o => o.cid));
  Object.keys(decisions).filter(k => !known.has(k)).forEach(k => problems.push(`review.json decides "${k}", which is not a candidate`));
  for (const o of rc.candidates) {
    if (!decisions[o.cid]) problems.push(`${o.cid}: no decision (every candidate needs one; nothing is skipped silently)`);
    else problems.push(...checkDecision(o, decisions[o.cid], { index, candidateById }));
  }
  const accepted = rc.candidates.filter(o => decisions[o.cid] && decisions[o.cid].decision === 'accept');
  if (!accepted.length) problems.push('no candidate is accepted: nothing to stage');
  if (accepted.length > MAX_STAGED) problems.push(`${accepted.length} accepted candidates exceed ${MAX_STAGED}; split the section`);
  if (problems.length) return refuse(problems);

  // the batch: accepted candidates only, ids = the importer's own derived ids (frozen from here on)
  const records = accepted.map(o => ({ id: o.importer.id, ...toImportRecord(candidateById.get(o.cid), rc.section_id) }));
  const idByCid = new Map(accepted.map(o => [o.cid, o.importer.id]));
  const idOf = ref => idByCid.get(ref) || rc.candidates.find(o => o.cid === ref && o.importer)?.importer.id || ref;
  // plan it as the importer will; every probable duplicate must be covered by the reviewer's reviewed_against -> a "distinct" decision
  const first = await probePlan({ sectionId: rc.section_id, records, index, root });
  const batchDecisions = {};
  for (const r of first.records.filter(x => x.class === 'probable-duplicate')) {
    const o = accepted.find(a => a.importer.id === r.id), dec = decisions[o.cid];
    const reviewed = new Set((dec.reviewed_against || []).map(idOf));
    const uncovered = r.candidates.map(x => x.id).filter(id => id && !reviewed.has(id));
    if (uncovered.length) problems.push(`${o.cid}: the importer's plan lists candidate(s) the review did not cover: ${uncovered.join(', ')}`);
    else batchDecisions[r.id] = { decision: 'distinct', reason: dec.reason.trim(), reviewed_against: [...reviewed].sort(byStr), reviewer: rv.reviewer };
  }
  first.records.filter(x => x.class !== 'new' && x.class !== 'probable-duplicate').forEach(x => problems.push(`${x.id}: the importer classes it ${x.class}; it cannot be staged`));
  if (problems.length) return refuse(problems);
  const final = await probePlan({ sectionId: rc.section_id, records, index, root, decisions: Object.keys(batchDecisions).length ? batchDecisions : null });
  if (!final.importable) return refuse(['the staged batch would not be importable:', ...final.blockers]);

  const tally = {}; Object.values(decisions).forEach(d => { tally[d.decision] = (tally[d.decision] || 0) + 1; });
  const meta = {
    schema_version: 1, batch_id: rc.section_id,
    description: `Regional research "${s.section.title}": ${records.length} new gym(s) accepted of ${rc.candidates.length} candidate(s)`,
    created: rv.reviewed,
    source: {
      kind: 'regional-research', section: `import/research/${rc.section_id}`,
      section_sha256: rc.inputs.section_sha256, sources_sha256: rc.inputs.sources_sha256, candidates_sha256: rc.inputs.candidates_sha256,
      reconcile_sha256: canonicalSha(rc), review_sha256: jsonSha(path.join(dir, FILES.review)),
      candidates: rc.candidates.length, staged: records.length, decisions: Object.fromEntries(Object.entries(tally).sort()),
    },
    index_at_staging: { sha256: index.sha256, count: index.entries.length },
  };
  const texts = { 'batch.json': JSON.stringify(meta, null, 2) + '\n', 'records.ndjson': records.map(r => JSON.stringify(r)).join('\n') + '\n' };
  if (Object.keys(batchDecisions).length) texts['decisions.json'] = JSON.stringify({ decisions: batchDecisions }, null, 2) + '\n';
  const out = path.join(batchesDir, rc.section_id);
  if (fs.existsSync(out)) {
    const same = Object.entries(texts).every(([f, t]) => fs.existsSync(path.join(out, f)) && fs.readFileSync(path.join(out, f), 'utf8') === t) && (texts['decisions.json'] || !fs.existsSync(path.join(out, 'decisions.json')));
    if (!same) return refuse([`import/batches/${rc.section_id} already exists and differs from what this review stages; never overwritten (if it was never imported, remove it deliberately and stage again)`]);
    return { action: 'unchanged', dir: out, staged: records.length, meta };
  }
  fs.mkdirSync(out, { recursive: true });
  for (const [f, t] of Object.entries(texts)) fs.writeFileSync(path.join(out, f), t);
  return { action: 'created', dir: out, staged: records.length, meta };
}

// ---- importer check: a staged regional-research batch still matches its section, record for record -------------------------
// Offline. Returns [{status, name, detail}] for importer.js. Any mismatch is a FAIL (the importer refuses; nothing is written).
function verifyStagedBatch({ root, batchId, meta, recs }) {
  const out = [], fail = (name, detail) => out.push({ status: 'FAIL', name, detail });
  const src = meta.source, rel = `import/research/${batchId}`, dir = path.join(root, 'import', 'research', batchId);
  if (src.section !== rel) { fail('provenance: research section', `batch.json source.section must be ${rel}`); return out; }
  if (!fs.existsSync(dir)) { fail('provenance: research section', `${rel} is missing; the batch cannot be traced to its research`); return out; }
  const files = [['section_sha256', FILES.section, jsonSha], ['sources_sha256', FILES.sources, jsonSha], ['candidates_sha256', FILES.candidates, ndjsonSha], ['reconcile_sha256', FILES.reconcile, jsonSha], ['review_sha256', FILES.review, jsonSha]];
  const changed = files.filter(([k, f, h]) => { try { return !fs.existsSync(path.join(dir, f)) || h(path.join(dir, f)) !== src[k]; } catch (e) { return true; } }).map(([, f]) => f);
  if (changed.length) { fail('provenance: research files unchanged since staging', `${changed.join(', ')} changed or missing; re-reconcile, re-review and stage a new section`); return out; }
  const rc = readJson(path.join(dir, FILES.reconcile)), rv = readJson(path.join(dir, FILES.review));
  const cands = new Map(ndjsonLines(fs.readFileSync(path.join(dir, FILES.candidates), 'utf8')).map(t => { try { return JSON.parse(t); } catch (e) { return null; } }).filter(c => c && typeof c.cid === 'string').map(c => [c.cid, c]));
  const accepted = new Set(Object.entries(rv.decisions || {}).filter(([, d]) => d && d.decision === 'accept').map(([cid]) => cid));
  const idOf = new Map((rc.candidates || []).filter(o => o.importer).map(o => [o.cid, o.importer.id]));
  const seen = new Set(), bad = [];
  for (const { line, rec } of recs) {
    const m = SOURCE_REF.exec(rec.source || '');
    if (!m || m[1] !== batchId) { bad.push(`line ${line}: source must be research:${batchId}#<cid>`); continue; }
    const cid = m[2];
    if (seen.has(cid)) bad.push(`line ${line}: ${cid} staged twice`);
    seen.add(cid);
    if (!accepted.has(cid)) bad.push(`line ${line}: ${cid} was not accepted in review.json`);
    else if (!cands.has(cid)) bad.push(`line ${line}: ${cid} is not in candidates.ndjson`);
    else if (JSON.stringify({ id: idOf.get(cid), ...toImportRecord(cands.get(cid), batchId) }) !== JSON.stringify(rec)) bad.push(`line ${line}: ${cid} differs from the reviewed candidate (records.ndjson was edited after staging)`);
  }
  [...accepted].filter(cid => !seen.has(cid)).forEach(cid => bad.push(`${cid} was accepted but is not in the batch`));
  if (bad.length) fail('provenance: batch = accepted research candidates', bad.slice(0, 6).join('; ') + (bad.length > 6 ? ` … (+${bad.length - 6})` : ''));
  else out.push({ status: 'PASS', name: 'provenance: regional research', detail: `${rel} unchanged; ${recs.length} record(s) = the ${accepted.size} accepted candidate(s), each identical to its reviewed candidate` });
  return out;
}

// ---- scaffold ---------------------------------------------------------------------------------------------------------------
async function newSection({ root, slug, date, country, states = null, bbox = null, title, description }) {
  if (!/^[a-z0-9][a-z0-9-]{1,60}$/.test(slug || '')) throw new Error('slug must be lower-case letters/digits/hyphens, e.g. "new-zealand"');
  if (!isDate(date)) throw new Error('date must be YYYY-MM-DD');
  const id = `${date}-${slug}`, dir = path.join(researchDir(root), id);
  if (fs.existsSync(dir)) throw new Error('research section already exists: ' + id);
  const section = { schema_version: SCHEMA_VERSION, section_id: id, title, description, created: date, scope: { country, states, bbox } };
  const problems = await checkSection({ id, section, problems: [] });
  if (problems.length) throw new Error('invalid section:\n  - ' + problems.join('\n  - '));
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, FILES.section), JSON.stringify(section, null, 2) + '\n');
  fs.writeFileSync(path.join(dir, FILES.sources), JSON.stringify({ schema_version: SCHEMA_VERSION, sources: {} }, null, 2) + '\n');
  fs.writeFileSync(path.join(dir, FILES.candidates), '');
  return { id, dir };
}

module.exports = { SCHEMA_VERSION, MAX_STAGED, FILES, R, PRIMARY_KINDS, REJECT_CODES, toImportRecord, checkCandidate, reconcile, renderReconcile, stage, verifyStagedBatch, newSection, sectionPath, loadSection };
