// STATES_BY_COUNTRY: every country's complete list of top-level divisions (large, static).
// `state` codes collide across countries (AU's WA = Western Australia, US's WA = Washington),
// so country+state together identify a region — never key off `state` alone.
// Every country here lists its REAL, COMPLETE set of top-level administrative
// divisions (all 50 US states + DC, all 47 JP prefectures, etc.) — not just
// the subset a prior seed-data pass happened to add spots in. This matters
// for the add/edit-spot forms (`populateStateSelect()` below): a community
// member proposing a gym in a state/province/prefecture with zero existing
// spots still needs to be able to select it. Fixed 2026-09 after a report
// that the Netherlands' dropdown only offered 3 of its 12 real provinces
// (missing Noord-Brabant, the one actually asked about) — audited and fixed
// for every country, not just NL. China (CN) is the one deliberate exception
// to "real administrative divisions": it intentionally lists major cities,
// not China's 34 provincial-level divisions (see `docs/architecture.md`
// "Data model" for why) — expanded here from 10 to 31 major/provincial-
// capital cities, still not exhaustive (China has 300+ prefecture-level
// cities), just a much wider practical set than before.
export const STATES_BY_COUNTRY = {
  AU: [['NSW','NSW'],['VIC','VIC'],['QLD','QLD'],['WA','WA'],['SA','SA'],['ACT','ACT'],['TAS','TAS'],['NT','NT']],
  US: [['AL','Alabama'],['AK','Alaska'],['AZ','Arizona'],['AR','Arkansas'],['CA','California'],['CO','Colorado'],
       ['CT','Connecticut'],['DE','Delaware'],['DC','District of Columbia'],['FL','Florida'],['GA','Georgia'],
       ['HI','Hawaii'],['ID','Idaho'],['IL','Illinois'],['IN','Indiana'],['IA','Iowa'],['KS','Kansas'],
       ['KY','Kentucky'],['LA','Louisiana'],['ME','Maine'],['MD','Maryland'],['MA','Massachusetts'],
       ['MI','Michigan'],['MN','Minnesota'],['MS','Mississippi'],['MO','Missouri'],['MT','Montana'],
       ['NE','Nebraska'],['NV','Nevada'],['NH','New Hampshire'],['NJ','New Jersey'],['NM','New Mexico'],
       ['NY','New York'],['NC','North Carolina'],['ND','North Dakota'],['OH','Ohio'],['OK','Oklahoma'],
       ['OR','Oregon'],['PA','Pennsylvania'],['RI','Rhode Island'],['SC','South Carolina'],['SD','South Dakota'],
       ['TN','Tennessee'],['TX','Texas'],['UT','Utah'],['VT','Vermont'],['VA','Virginia'],['WA','Washington'],
       ['WV','West Virginia'],['WI','Wisconsin'],['WY','Wyoming']],
  JP: [['AICHI','Aichi (Nagoya)'],['AKITA','Akita'],['AOMORI','Aomori'],['CHIBA','Chiba'],['EHIME','Ehime'],
       ['FUKUI','Fukui'],['FUKUOKA','Fukuoka'],['FUKUSHIMA','Fukushima'],['GIFU','Gifu'],['GUNMA','Gunma'],
       ['HIROSHIMA','Hiroshima'],['HOKKAIDO','Hokkaido (Sapporo)'],['HYOGO','Hyogo (Kobe)'],['IBARAKI','Ibaraki'],
       ['ISHIKAWA','Ishikawa'],['IWATE','Iwate'],['KAGAWA','Kagawa'],['KAGOSHIMA','Kagoshima'],
       ['KANAGAWA','Kanagawa (Yokohama)'],['KOCHI','Kochi'],['KUMAMOTO','Kumamoto'],['KYOTO','Kyoto'],
       ['MIE','Mie'],['MIYAGI','Miyagi'],['MIYAZAKI','Miyazaki'],['NAGANO','Nagano'],['NAGASAKI','Nagasaki'],
       ['NARA','Nara'],['NIIGATA','Niigata'],['OITA','Oita'],['OKAYAMA','Okayama'],['OKINAWA','Okinawa'],
       ['OSAKA','Osaka'],['SAGA','Saga'],['SAITAMA','Saitama'],['SHIGA','Shiga'],['SHIMANE','Shimane'],
       ['SHIZUOKA','Shizuoka'],['TOCHIGI','Tochigi'],['TOKUSHIMA','Tokushima'],['TOKYO','Tokyo'],
       ['TOTTORI','Tottori'],['TOYAMA','Toyama'],['WAKAYAMA','Wakayama'],['YAMAGATA','Yamagata'],
       ['YAMAGUCHI','Yamaguchi'],['YAMANASHI','Yamanashi']],
  CA: [['AB','Alberta'],['BC','British Columbia'],['MB','Manitoba'],['NB','New Brunswick'],
       ['NL','Newfoundland and Labrador'],['NT','Northwest Territories'],['NS','Nova Scotia'],['NU','Nunavut'],
       ['ON','Ontario'],['PE','Prince Edward Island'],['QC','Quebec'],['SK','Saskatchewan'],['YT','Yukon']],
  NZ: [['AUCKLAND','Auckland'],['BAY_OF_PLENTY','Bay of Plenty'],['CANTERBURY','Canterbury (Christchurch)'],
       ['GISBORNE','Gisborne'],['HAWKES_BAY',"Hawke's Bay"],['MANAWATU_WHANGANUI','Manawatu-Whanganui'],
       ['MARLBOROUGH','Marlborough'],['NELSON','Nelson'],['NORTHLAND','Northland'],['OTAGO','Otago'],
       ['SOUTHLAND','Southland'],['TARANAKI','Taranaki'],['TASMAN','Tasman'],['WAIKATO','Waikato'],
       ['WELLINGTON','Wellington'],['WEST_COAST','West Coast']],
  CN: [['BEIJING','Beijing'],['CHANGCHUN','Changchun'],['CHANGSHA','Changsha'],['CHENGDU','Chengdu'],
       ['CHONGQING','Chongqing'],['DALIAN','Dalian'],['FUZHOU','Fuzhou'],['GUANGZHOU','Guangzhou'],
       ['GUIYANG','Guiyang'],['HAIKOU','Haikou'],['HANGZHOU','Hangzhou'],['HARBIN','Harbin'],['HEFEI','Hefei'],
       ['JINAN','Jinan'],['KUNMING','Kunming'],['NANCHANG','Nanchang'],['NANJING','Nanjing'],
       ['NANNING','Nanning'],['NINGBO','Ningbo'],['QINGDAO','Qingdao'],['SHANGHAI','Shanghai'],
       ['SHENYANG','Shenyang'],['SHENZHEN','Shenzhen'],['SHIJIAZHUANG','Shijiazhuang'],['SUZHOU','Suzhou'],
       ['TIANJIN','Tianjin'],['WUHAN','Wuhan'],['XIAMEN','Xiamen'],['XIAN',"Xi'an"],['ZHENGZHOU','Zhengzhou'],
       ['ZHUHAI','Zhuhai']],
  GB: [['ENGLAND','England'],['SCOTLAND','Scotland'],['WALES','Wales'],['NORTHERN_IRELAND','Northern Ireland']],
  DE: [['BAYERN','Bayern'],['BERLIN','Berlin'],['NORDRHEIN_WESTFALEN','Nordrhein-Westfalen'],['HESSEN','Hessen'],
       ['BADEN_WURTTEMBERG','Baden-Württemberg'],['BREMEN','Bremen'],['SCHLESWIG_HOLSTEIN','Schleswig-Holstein'],
       ['SACHSEN','Sachsen'],['NIEDERSACHSEN','Niedersachsen'],['SACHSEN_ANHALT','Sachsen-Anhalt'],
       ['BRANDENBURG','Brandenburg'],['RHEINLAND_PFALZ','Rheinland-Pfalz'],['HAMBURG','Hamburg'],
       ['SAARLAND','Saarland'],['THURINGEN','Thüringen'],['MECKLENBURG_VORPOMMERN','Mecklenburg-Vorpommern']],
  FR: [['AUVERGNE_RHONE_ALPES','Auvergne-Rhône-Alpes (Lyon)'],['BOURGOGNE_FRANCHE_COMTE','Bourgogne-Franche-Comté'],
       ['BRETAGNE','Bretagne'],['CENTRE_VAL_DE_LOIRE','Centre-Val de Loire'],['CORSE','Corse'],
       ['GRAND_EST','Grand Est'],['HAUTS_DE_FRANCE','Hauts-de-France'],['ILE_DE_FRANCE','Île-de-France (Paris)'],
       ['NORMANDIE','Normandie'],['NOUVELLE_AQUITAINE','Nouvelle-Aquitaine'],['OCCITANIE','Occitanie (Toulouse)'],
       ['PAYS_DE_LA_LOIRE','Pays de la Loire'],['PACA',"Provence-Alpes-Côte d'Azur (Marseille)"]],
  SE: [['BLEKINGE','Blekinge'],['DALARNA','Dalarna'],['GAVLEBORG','Gävleborg'],['GOTLAND','Gotland'],
       ['HALLAND','Halland'],['JAMTLAND','Jämtland'],['JONKOPING','Jönköping'],['KALMAR','Kalmar'],
       ['KRONOBERG','Kronoberg'],['NORRBOTTEN','Norrbotten'],['OREBRO','Örebro'],['OSTERGOTLAND','Östergötland'],
       ['SKANE','Skåne (Malmö)'],['SODERMANLAND','Södermanland'],['STOCKHOLM','Stockholm'],['UPPSALA','Uppsala'],
       ['VARMLAND','Värmland'],['VASTERBOTTEN','Västerbotten'],['VASTERNORRLAND','Västernorrland'],
       ['VASTMANLAND','Västmanland'],['VASTRA_GOTALAND','Västra Götaland (Göteborg)']],
  NL: [['DRENTHE','Drenthe'],['FLEVOLAND','Flevoland'],['FRIESLAND','Friesland (Fryslân)'],
       ['GELDERLAND','Gelderland'],['GRONINGEN','Groningen'],['LIMBURG','Limburg'],
       ['NOORD_BRABANT','Noord-Brabant'],['NOORD_HOLLAND','Noord-Holland (Amsterdam)'],['OVERIJSSEL','Overijssel'],
       ['UTRECHT','Utrecht'],['ZEELAND','Zeeland'],['ZUID_HOLLAND','Zuid-Holland (Den Haag, Rotterdam)']],
  IT: [['ABRUZZO','Abruzzo'],['BASILICATA','Basilicata'],['CALABRIA','Calabria'],['CAMPANIA','Campania'],
       ['EMILIA_ROMAGNA','Emilia-Romagna (Modena)'],['FRIULI_VENEZIA_GIULIA','Friuli-Venezia Giulia'],
       ['LAZIO','Lazio (Roma)'],['LIGURIA','Liguria'],['LOMBARDIA','Lombardia (Milano)'],['MARCHE','Marche'],
       ['MOLISE','Molise'],['PIEMONTE','Piemonte'],['PUGLIA','Puglia'],['SARDEGNA','Sardegna'],
       ['SICILIA','Sicilia'],['TOSCANA','Toscana (Firenze)'],['TRENTINO_ALTO_ADIGE','Trentino-Alto Adige'],
       ['UMBRIA','Umbria'],['VALLE_DAOSTA',"Valle d'Aosta"],['VENETO','Veneto']],
  BE: [['FLANDERS','Flanders'],['WALLONIA','Wallonia'],['BRUSSELS','Brussels-Capital']],
  KR: [['BUSAN','Busan'],['CHUNGCHEONGBUK','Chungcheongbuk-do'],['CHUNGCHEONGNAM','Chungcheongnam-do'],
       ['DAEGU','Daegu'],['DAEJEON','Daejeon'],['GANGWON','Gangwon-do'],['GWANGJU','Gwangju'],
       ['GYEONGGI','Gyeonggi-do'],['GYEONGSANGBUK','Gyeongsangbuk-do'],['GYEONGSANGNAM','Gyeongsangnam-do'],
       ['INCHEON','Incheon'],['JEJU','Jeju'],['JEOLLABUK','Jeollabuk-do'],['JEOLLANAM','Jeollanam-do'],
       ['SEJONG','Sejong'],['SEOUL','Seoul'],['ULSAN','Ulsan']],
  ES: [['ANDALUCIA','Andalucía'],['ARAGON','Aragón'],['ASTURIAS','Asturias'],['BALEARES','Baleares'],
       ['CANARIAS','Canarias'],['CANTABRIA','Cantabria'],['CASTILLA_LA_MANCHA','Castilla-La Mancha'],
       ['CASTILLA_Y_LEON','Castilla y León'],['CATALUNYA','Cataluña (Barcelona)'],['CEUTA','Ceuta'],
       ['MADRID','Comunidad de Madrid'],['COMUNIDAD_VALENCIANA','Comunidad Valenciana'],
       ['EXTREMADURA','Extremadura'],['GALICIA','Galicia'],['LA_RIOJA','La Rioja'],['MELILLA','Melilla'],
       ['MURCIA','Murcia'],['NAVARRA','Navarra'],['PAIS_VASCO','País Vasco']],
  PT: [['ACORES','Açores'],['AVEIRO','Aveiro'],['BEJA','Beja'],['BRAGA','Braga'],['BRAGANCA','Bragança'],
       ['CASTELO_BRANCO','Castelo Branco'],['COIMBRA','Coimbra'],['EVORA','Évora'],['FARO','Faro'],
       ['GUARDA','Guarda'],['LEIRIA','Leiria'],['LISBOA','Lisboa'],['MADEIRA','Madeira'],
       ['PORTALEGRE','Portalegre'],['PORTO','Porto'],['SANTAREM','Santarém'],['SETUBAL','Setúbal'],
       ['VIANA_DO_CASTELO','Viana do Castelo'],['VILA_REAL','Vila Real'],['VISEU','Viseu']],
  AT: [['BURGENLAND','Burgenland'],['KARNTEN','Kärnten'],['NIEDEROSTERREICH','Niederösterreich'],
       ['OBEROSTERREICH','Oberösterreich (Linz)'],['SALZBURG','Salzburg'],['STEIERMARK','Steiermark (Graz)'],
       ['TIROL','Tirol'],['VORARLBERG','Vorarlberg'],['WIEN','Wien']],
  CH: [['AARGAU','Aargau'],['APPENZELL_AUSSERRHODEN','Appenzell Ausserrhoden'],
       ['APPENZELL_INNERRHODEN','Appenzell Innerrhoden'],['BASEL_LANDSCHAFT','Basel-Landschaft'],
       ['BASEL_STADT','Basel-Stadt (Basel)'],['BERN','Bern'],['FRIBOURG','Fribourg'],['GENEVE','Genève'],
       ['GLARUS','Glarus'],['GRAUBUNDEN','Graubünden'],['JURA','Jura'],['LUZERN','Luzern'],
       ['NEUCHATEL','Neuchâtel'],['NIDWALDEN','Nidwalden'],['OBWALDEN','Obwalden'],
       ['SCHAFFHAUSEN','Schaffhausen'],['SCHWYZ','Schwyz'],['SOLOTHURN','Solothurn'],['ST_GALLEN','St. Gallen'],
       ['THURGAU','Thurgau'],['TICINO','Ticino'],['URI','Uri'],['VALAIS','Valais'],['VAUD','Vaud'],
       ['ZUG','Zug'],['ZURICH','Zürich (Winterthur)']],
  PL: [['DOLNOSLASKIE','Dolnośląskie (Wrocław)'],['KUJAWSKO_POMORSKIE','Kujawsko-Pomorskie'],
       ['LUBELSKIE','Lubelskie'],['LUBUSKIE','Lubuskie'],['LODZKIE','Łódzkie'],
       ['MALOPOLSKIE','Małopolskie (Kraków)'],['MAZOWIECKIE','Mazowieckie (Warszawa)'],['OPOLSKIE','Opolskie'],
       ['PODKARPACKIE','Podkarpackie'],['PODLASKIE','Podlaskie'],['POMORSKIE','Pomorskie'],
       ['SLASKIE','Śląskie'],['SWIETOKRZYSKIE','Świętokrzyskie'],
       ['WARMINSKO_MAZURSKIE','Warmińsko-Mazurskie'],['WIELKOPOLSKIE','Wielkopolskie (Poznań)'],
       ['ZACHODNIOPOMORSKIE','Zachodniopomorskie']],
  DK: [['HOVEDSTADEN','Hovedstaden (København)'],['MIDTJYLLAND','Midtjylland (Aarhus)'],
       ['NORDJYLLAND','Nordjylland (Aalborg)'],['SJAELLAND','Sjælland'],['SYDDANMARK','Syddanmark (Odense)']],
  FI: [['AHVENANMAA','Ahvenanmaa'],['ETELA_KARJALA','Etelä-Karjala'],['ETELA_POHJANMAA','Etelä-Pohjanmaa'],
       ['ETELA_SAVO','Etelä-Savo'],['KAINUU','Kainuu'],['KANTA_HAME','Kanta-Häme'],
       ['KESKI_POHJANMAA','Keski-Pohjanmaa'],['KESKI_SUOMI','Keski-Suomi'],['KYMENLAAKSO','Kymenlaakso'],
       ['LAPPI','Lappi'],['PIRKANMAA','Pirkanmaa (Tampere)'],['POHJANMAA','Pohjanmaa'],
       ['POHJOIS_KARJALA','Pohjois-Karjala'],['POHJOIS_POHJANMAA','Pohjois-Pohjanmaa (Oulu)'],
       ['POHJOIS_SAVO','Pohjois-Savo'],['PAIJAT_HAME','Päijät-Häme (Lahti)'],['SATAKUNTA','Satakunta'],
       ['UUSIMAA','Uusimaa (Helsinki)'],['VARSINAIS_SUOMI','Varsinais-Suomi']],
  IE: [['CARLOW','Carlow'],['CAVAN','Cavan'],['CLARE','Clare'],['CORK','Cork'],['DONEGAL','Donegal'],
       ['DUBLIN','Dublin'],['GALWAY','Galway'],['KERRY','Kerry'],['KILDARE','Kildare'],['KILKENNY','Kilkenny'],
       ['LAOIS','Laois'],['LEITRIM','Leitrim'],['LIMERICK','Limerick'],['LONGFORD','Longford'],
       ['LOUTH','Louth'],['MAYO','Mayo'],['MEATH','Meath'],['MONAGHAN','Monaghan'],['OFFALY','Offaly'],
       ['ROSCOMMON','Roscommon'],['SLIGO','Sligo'],['TIPPERARY','Tipperary'],['WATERFORD','Waterford'],
       ['WESTMEATH','Westmeath'],['WEXFORD','Wexford'],['WICKLOW','Wicklow']],
  NO: [['AGDER','Agder (Kristiansand)'],['AKERSHUS','Akershus'],['BUSKERUD','Buskerud (Hemsedal)'],
       ['FINNMARK','Finnmark'],['INNLANDET','Innlandet (Lillehammer)'],
       ['MORE_OG_ROMSDAL','Møre og Romsdal (Ålesund, Kristiansund)'],['NORDLAND','Nordland (Bodø)'],
       ['OSLO','Oslo'],['ROGALAND','Rogaland (Stavanger)'],['TELEMARK','Telemark (Skien)'],
       ['TROMS','Troms'],['TRONDELAG','Trøndelag (Trondheim)'],['VESTFOLD','Vestfold'],
       ['VESTLAND','Vestland (Bergen)'],['OSTFOLD','Østfold']],
  MX: [['AGUASCALIENTES','Aguascalientes'],['BAJA_CALIFORNIA','Baja California'],
       ['BAJA_CALIFORNIA_SUR','Baja California Sur'],['CAMPECHE','Campeche'],['CHIAPAS','Chiapas'],
       ['CHIHUAHUA','Chihuahua'],['CIUDAD_DE_MEXICO','Ciudad de México'],['COAHUILA','Coahuila'],
       ['COLIMA','Colima'],['DURANGO','Durango'],['GUANAJUATO','Guanajuato'],['GUERRERO','Guerrero'],
       ['HIDALGO','Hidalgo'],['JALISCO','Jalisco (Zapopan)'],['MEXICO','México (Toluca)'],
       ['MICHOACAN','Michoacán'],['MORELOS','Morelos'],['NAYARIT','Nayarit'],
       ['NUEVO_LEON','Nuevo León (Monterrey)'],['OAXACA','Oaxaca'],['PUEBLA','Puebla'],
       ['QUERETARO','Querétaro'],['QUINTANA_ROO','Quintana Roo'],['SAN_LUIS_POTOSI','San Luis Potosí'],
       ['SINALOA','Sinaloa'],['SONORA','Sonora'],['TABASCO','Tabasco'],['TAMAULIPAS','Tamaulipas'],
       ['TLAXCALA','Tlaxcala'],['VERACRUZ','Veracruz'],['YUCATAN','Yucatán'],['ZACATECAS','Zacatecas']],
  BR: [['ACRE','Acre'],['ALAGOAS','Alagoas'],['AMAPA','Amapá'],['AMAZONAS','Amazonas'],['BAHIA','Bahia'],
       ['CEARA','Ceará'],['DISTRITO_FEDERAL','Distrito Federal'],['ESPIRITO_SANTO','Espírito Santo'],
       ['GOIAS','Goiás'],['MARANHAO','Maranhão'],['MATO_GROSSO','Mato Grosso'],
       ['MATO_GROSSO_DO_SUL','Mato Grosso do Sul'],['MINAS_GERAIS','Minas Gerais (Belo Horizonte)'],
       ['PARA','Pará'],['PARAIBA','Paraíba'],['PARANA','Paraná (Curitiba)'],['PERNAMBUCO','Pernambuco'],
       ['PIAUI','Piauí'],['RIO_DE_JANEIRO','Rio de Janeiro'],['RIO_GRANDE_DO_NORTE','Rio Grande do Norte'],
       ['RIO_GRANDE_DO_SUL','Rio Grande do Sul'],['RONDONIA','Rondônia'],['RORAIMA','Roraima'],
       ['SANTA_CATARINA','Santa Catarina'],['SAO_PAULO','São Paulo'],['SERGIPE','Sergipe'],
       ['TOCANTINS','Tocantins']],
  HU: [['BACS_KISKUN','Bács-Kiskun'],['BARANYA','Baranya'],['BEKES','Békés'],
       ['BORSOD_ABAUJ_ZEMPLEN','Borsod-Abaúj-Zemplén'],['BUDAPEST','Budapest'],
       ['CSONGRAD_CSANAD','Csongrád-Csanád'],['FEJER','Fejér'],['GYOR_MOSON_SOPRON','Győr-Moson-Sopron'],
       ['HAJDU_BIHAR','Hajdú-Bihar'],['HEVES','Heves'],['JASZ_NAGYKUN_SZOLNOK','Jász-Nagykun-Szolnok'],
       ['KOMAROM_ESZTERGOM','Komárom-Esztergom'],['NOGRAD','Nógrád'],['PEST','Pest'],['SOMOGY','Somogy'],
       ['SZABOLCS_SZATMAR_BEREG','Szabolcs-Szatmár-Bereg'],['TOLNA','Tolna'],['VAS','Vas'],
       ['VESZPREM','Veszprém'],['ZALA','Zala']],
  GR: [['ATTICA','Attica'],['CENTRAL_GREECE','Central Greece'],['CENTRAL_MACEDONIA','Central Macedonia'],
       ['CRETE','Crete'],['EASTERN_MACEDONIA_THRACE','Eastern Macedonia and Thrace'],['EPIRUS','Epirus'],
       ['IONIAN_ISLANDS','Ionian Islands'],['NORTH_AEGEAN','North Aegean'],['PELOPONNESE','Peloponnese'],
       ['SOUTH_AEGEAN','South Aegean'],['THESSALY','Thessaly'],['WESTERN_GREECE','Western Greece'],
       ['WESTERN_MACEDONIA','Western Macedonia']],
  CZ: [['JIHOCESKY','Jihočeský (South Bohemia)'],['JIHOMORAVSKY','Jihomoravský (South Moravia)'],
       ['KARLOVARSKY','Karlovarský'],['KRALOVEHRADECKY','Královéhradecký'],['LIBERECKY','Liberecký'],
       ['MORAVSKOSLEZSKY','Moravskoslezský'],['OLOMOUCKY','Olomoucký'],['PARDUBICKY','Pardubický'],
       ['PLZENSKY','Plzeňský'],['PRAHA','Praha (Prague)'],['STREDOCESKY','Středočeský'],
       ['USTECKY','Ústecký'],['VYSOCINA','Vysočina'],['ZLINSKY','Zlínský']],
  IS: [['AUSTURLAND','Austurland (East)'],['HOFUDBORGARSVAEDID','Höfuðborgarsvæðið (Capital Region)'],
       ['NORDURLAND_EYSTRA','Norðurland eystra (Northeast)'],['NORDURLAND_VESTRA','Norðurland vestra (Northwest)'],
       ['SUDURLAND','Suðurland (South)'],['SUDURNES','Suðurnes'],['VESTFIRDIR','Vestfirðir (Westfjords)'],
       ['VESTURLAND','Vesturland (West)']],
  RO: [['ALBA','Alba'],['ARAD','Arad'],['ARGES','Argeș'],['BACAU','Bacău'],['BIHOR','Bihor'],
       ['BISTRITA_NASAUD','Bistrița-Năsăud'],['BOTOSANI','Botoșani'],['BRAILA','Brăila'],['BRASOV','Brașov'],
       ['BUCURESTI','București'],['BUZAU','Buzău'],['CALARASI','Călărași'],['CARAS_SEVERIN','Caraș-Severin'],
       ['CLUJ','Cluj'],['CONSTANTA','Constanța'],['COVASNA','Covasna'],['DAMBOVITA','Dâmbovița'],
       ['DOLJ','Dolj'],['GALATI','Galați'],['GIURGIU','Giurgiu'],['GORJ','Gorj'],['HARGHITA','Harghita'],
       ['HUNEDOARA','Hunedoara'],['IALOMITA','Ialomița'],['IASI','Iași'],['ILFOV','Ilfov'],
       ['MARAMURES','Maramureș'],['MEHEDINTI','Mehedinți'],['MURES','Mureș'],['NEAMT','Neamț'],
       ['OLT','Olt'],['PRAHOVA','Prahova'],['SALAJ','Sălaj'],['SATU_MARE','Satu Mare'],['SIBIU','Sibiu'],
       ['SUCEAVA','Suceava'],['TELEORMAN','Teleorman'],['TIMIS','Timiș'],['TULCEA','Tulcea'],
       ['VALCEA','Vâlcea'],['VASLUI','Vaslui'],['VRANCEA','Vrancea']],
  HR: [['BJELOVAR_BILOGORA','Bjelovar-Bilogora'],['BROD_POSAVINA','Brod-Posavina'],
       ['DUBROVNIK_NERETVA','Dubrovnik-Neretva'],['ISTARSKA','Istarska'],['KARLOVAC','Karlovac'],
       ['KOPRIVNICKO_KRIZEVACKA','Koprivničko-križevačka'],['KRAPINA_ZAGORJE','Krapina-Zagorje'],
       ['LIKA_SENJ','Lika-Senj'],['MEDIMURJE','Međimurje'],['OSIJEK_BARANJA','Osijek-Baranja'],
       ['POZEGA_SLAVONIJA','Požega-Slavonija'],['PRIMORJE_GORSKI_KOTAR','Primorje-Gorski Kotar'],
       ['SIBENIK_KNIN','Šibenik-Knin'],['SISAK_MOSLAVINA','Sisak-Moslavina'],
       ['SPLITSKO_DALMATINSKA','Splitsko-dalmatinska'],['VARAZDIN','Varaždin'],
       ['VIROVITICA_PODRAVINA','Virovitica-Podravina'],['VUKOVAR_SRIJEM','Vukovar-Srijem'],['ZADAR','Zadar'],
       ['ZAGREBACKA','Zagrebačka'],['ZAGREB','Zagreb']],
  RU: [['MOSKVA','Moskva'],['SANKT_PETERBURG','Sankt-Peterburg'],['NOVOSIBIRSK','Novosibirsk'],
       ['YEKATERINBURG','Yekaterinburg'],['KAZAN','Kazan'],['NIZHNY_NOVGOROD','Nizhny Novgorod'],
       ['CHELYABINSK','Chelyabinsk'],['KRASNOYARSK','Krasnoyarsk'],['SAMARA','Samara'],['UFA','Ufa'],
       ['ROSTOV_ON_DON','Rostov-on-Don'],['OMSK','Omsk'],['KRASNODAR','Krasnodar'],['VORONEZH','Voronezh'],
       ['PERM','Perm'],['VOLGOGRAD','Volgograd'],['SARATOV','Saratov'],['TYUMEN','Tyumen'],
       ['TOLYATTI','Tolyatti'],['IZHEVSK','Izhevsk']],
  BG: [['BLAGOEVGRAD','Blagoevgrad'],['BURGAS','Burgas'],['DOBRICH','Dobrich'],['GABROVO','Gabrovo'],
       ['HASKOVO','Haskovo'],['KARDZHALI','Kardzhali'],['KYUSTENDIL','Kyustendil'],['LOVECH','Lovech'],
       ['MONTANA','Montana'],['PAZARDZHIK','Pazardzhik'],['PERNIK','Pernik'],['PLEVEN','Pleven'],
       ['PLOVDIV','Plovdiv'],['RAZGRAD','Razgrad'],['RUSE','Ruse'],['SHUMEN','Shumen'],
       ['SILISTRA','Silistra'],['SLIVEN','Sliven'],['SMOLYAN','Smolyan'],['SOFIA_CITY','Sofia City'],
       ['SOFIA','Sofia (province)'],['STARA_ZAGORA','Stara Zagora'],['TARGOVISHTE','Targovishte'],
       ['VARNA','Varna'],['VELIKO_TARNOVO','Veliko Tarnovo'],['VIDIN','Vidin'],['VRATSA','Vratsa'],
       ['YAMBOL','Yambol']],
  AR: [['BUENOS_AIRES','Buenos Aires'],['CABA','Ciudad Autónoma de Buenos Aires'],['CATAMARCA','Catamarca'],
       ['CHACO','Chaco'],['CHUBUT','Chubut'],['CORDOBA','Córdoba'],['CORRIENTES','Corrientes'],
       ['ENTRE_RIOS','Entre Ríos'],['FORMOSA','Formosa'],['JUJUY','Jujuy'],['LA_PAMPA','La Pampa'],
       ['LA_RIOJA','La Rioja'],['MENDOZA','Mendoza'],['MISIONES','Misiones'],['NEUQUEN','Neuquén'],
       ['RIO_NEGRO','Río Negro'],['SALTA','Salta'],['SAN_JUAN','San Juan'],['SAN_LUIS','San Luis'],
       ['SANTA_CRUZ','Santa Cruz'],['SANTA_FE','Santa Fe'],['SANTIAGO_DEL_ESTERO','Santiago del Estero'],
       ['TIERRA_DEL_FUEGO','Tierra del Fuego'],['TUCUMAN','Tucumán']],
  PH: [['NCR','National Capital Region (Metro Manila)'],['ABRA','Abra'],['AGUSAN_DEL_NORTE','Agusan del Norte'],
       ['AGUSAN_DEL_SUR','Agusan del Sur'],['AKLAN','Aklan'],['ALBAY','Albay'],['ANTIQUE','Antique'],
       ['APAYAO','Apayao'],['AURORA','Aurora'],['BASILAN','Basilan'],['BATAAN','Bataan'],['BATANES','Batanes'],
       ['BATANGAS','Batangas'],['BENGUET','Benguet'],['BILIRAN','Biliran'],['BOHOL','Bohol'],
       ['BUKIDNON','Bukidnon'],['BULACAN','Bulacan'],['CAGAYAN','Cagayan'],['CAMARINES_NORTE','Camarines Norte'],
       ['CAMARINES_SUR','Camarines Sur'],['CAMIGUIN','Camiguin'],['CAPIZ','Capiz'],['CATANDUANES','Catanduanes'],
       ['CAVITE','Cavite'],['CEBU','Cebu'],['COTABATO','Cotabato'],['DAVAO_DE_ORO','Davao de Oro'],
       ['DAVAO_DEL_NORTE','Davao del Norte'],['DAVAO_DEL_SUR','Davao del Sur'],['DAVAO_OCCIDENTAL','Davao Occidental'],
       ['DAVAO_ORIENTAL','Davao Oriental'],['DINAGAT_ISLANDS','Dinagat Islands'],['EASTERN_SAMAR','Eastern Samar'],
       ['GUIMARAS','Guimaras'],['IFUGAO','Ifugao'],['ILOCOS_NORTE','Ilocos Norte'],['ILOCOS_SUR','Ilocos Sur'],
       ['ILOILO','Iloilo'],['ISABELA','Isabela'],['KALINGA','Kalinga'],['LA_UNION','La Union'],['LAGUNA','Laguna'],
       ['LANAO_DEL_NORTE','Lanao del Norte'],['LANAO_DEL_SUR','Lanao del Sur'],['LEYTE','Leyte'],
       ['MAGUINDANAO_DEL_NORTE','Maguindanao del Norte'],['MAGUINDANAO_DEL_SUR','Maguindanao del Sur'],
       ['MARINDUQUE','Marinduque'],['MASBATE','Masbate'],['MISAMIS_OCCIDENTAL','Misamis Occidental'],
       ['MISAMIS_ORIENTAL','Misamis Oriental'],['MOUNTAIN_PROVINCE','Mountain Province'],
       ['NEGROS_OCCIDENTAL','Negros Occidental'],['NEGROS_ORIENTAL','Negros Oriental'],
       ['NORTHERN_SAMAR','Northern Samar'],['NUEVA_ECIJA','Nueva Ecija'],['NUEVA_VIZCAYA','Nueva Vizcaya'],
       ['OCCIDENTAL_MINDORO','Occidental Mindoro'],['ORIENTAL_MINDORO','Oriental Mindoro'],['PALAWAN','Palawan'],
       ['PAMPANGA','Pampanga'],['PANGASINAN','Pangasinan'],['QUEZON','Quezon'],['QUIRINO','Quirino'],
       ['RIZAL','Rizal'],['ROMBLON','Romblon'],['SAMAR','Samar'],['SARANGANI','Sarangani'],['SIQUIJOR','Siquijor'],
       ['SORSOGON','Sorsogon'],['SOUTH_COTABATO','South Cotabato'],['SOUTHERN_LEYTE','Southern Leyte'],
       ['SULTAN_KUDARAT','Sultan Kudarat'],['SULU','Sulu'],['SURIGAO_DEL_NORTE','Surigao del Norte'],
       ['SURIGAO_DEL_SUR','Surigao del Sur'],['TARLAC','Tarlac'],['TAWI_TAWI','Tawi-Tawi'],['ZAMBALES','Zambales'],
       ['ZAMBOANGA_DEL_NORTE','Zamboanga del Norte'],['ZAMBOANGA_DEL_SUR','Zamboanga del Sur'],
       ['ZAMBOANGA_SIBUGAY','Zamboanga Sibugay']],
  CO: [['AMAZONAS','Amazonas'],['ANTIOQUIA','Antioquia'],['ARAUCA','Arauca'],['ATLANTICO','Atlántico'],
       ['BOGOTA_DC','Bogotá D.C.'],['BOLIVAR','Bolívar'],['BOYACA','Boyacá'],['CALDAS','Caldas'],
       ['CAQUETA','Caquetá'],['CASANARE','Casanare'],['CAUCA','Cauca'],['CESAR','Cesar'],['CHOCO','Chocó'],
       ['CORDOBA','Córdoba'],['CUNDINAMARCA','Cundinamarca'],['GUAINIA','Guainía'],['GUAVIARE','Guaviare'],
       ['HUILA','Huila'],['LA_GUAJIRA','La Guajira'],['MAGDALENA','Magdalena'],['META','Meta'],
       ['NARINO','Nariño'],['NORTE_DE_SANTANDER','Norte de Santander'],['PUTUMAYO','Putumayo'],
       ['QUINDIO','Quindío'],['RISARALDA','Risaralda'],['SAN_ANDRES_Y_PROVIDENCIA','San Andrés y Providencia'],
       ['SANTANDER','Santander'],['SUCRE','Sucre'],['TOLIMA','Tolima'],['VALLE_DEL_CAUCA','Valle del Cauca'],
       ['VAUPES','Vaupés'],['VICHADA','Vichada']],
  CL: [['ARICA_Y_PARINACOTA','Arica y Parinacota'],['TARAPACA','Tarapacá'],['ANTOFAGASTA','Antofagasta'],
       ['ATACAMA','Atacama'],['COQUIMBO','Coquimbo'],['VALPARAISO','Valparaíso'],
       ['METROPOLITANA','Metropolitana de Santiago'],['LIBERTADOR_OHIGGINS',"Libertador General Bernardo O'Higgins"],
       ['MAULE','Maule'],['NUBLE','Ñuble'],['BIOBIO','Biobío'],['ARAUCANIA','La Araucanía'],
       ['LOS_RIOS','Los Ríos'],['LOS_LAGOS','Los Lagos'],['AYSEN','Aysén'],
       ['MAGALLANES','Magallanes y de la Antártica Chilena']],
  VE: [['AMAZONAS','Amazonas'],['ANZOATEGUI','Anzoátegui'],['APURE','Apure'],['ARAGUA','Aragua'],
       ['BARINAS','Barinas'],['BOLIVAR','Bolívar'],['CARABOBO','Carabobo'],['COJEDES','Cojedes'],
       ['DELTA_AMACURO','Delta Amacuro'],['DISTRITO_CAPITAL','Distrito Capital'],['FALCON','Falcón'],
       ['GUARICO','Guárico'],['LARA','Lara'],['LA_GUAIRA','La Guaira'],['MERIDA','Mérida'],
       ['MIRANDA','Miranda'],['MONAGAS','Monagas'],['NUEVA_ESPARTA','Nueva Esparta'],
       ['PORTUGUESA','Portuguesa'],['SUCRE','Sucre'],['TACHIRA','Táchira'],['TRUJILLO','Trujillo'],
       ['YARACUY','Yaracuy'],['ZULIA','Zulia']],
  IN: [['ANDAMAN_AND_NICOBAR','Andaman and Nicobar Islands'],['ANDHRA_PRADESH','Andhra Pradesh'],
       ['ARUNACHAL_PRADESH','Arunachal Pradesh'],['ASSAM','Assam'],['BIHAR','Bihar'],
       ['CHANDIGARH','Chandigarh'],['CHHATTISGARH','Chhattisgarh'],
       ['DADRA_NAGAR_HAVELI_DAMAN_DIU','Dadra and Nagar Haveli and Daman and Diu'],['DELHI','Delhi (NCT)'],
       ['GOA','Goa'],['GUJARAT','Gujarat'],['HARYANA','Haryana'],['HIMACHAL_PRADESH','Himachal Pradesh'],
       ['JAMMU_AND_KASHMIR','Jammu and Kashmir'],['JHARKHAND','Jharkhand'],['KARNATAKA','Karnataka'],
       ['KERALA','Kerala'],['LADAKH','Ladakh'],['LAKSHADWEEP','Lakshadweep'],
       ['MADHYA_PRADESH','Madhya Pradesh'],['MAHARASHTRA','Maharashtra'],['MANIPUR','Manipur'],
       ['MEGHALAYA','Meghalaya'],['MIZORAM','Mizoram'],['NAGALAND','Nagaland'],['ODISHA','Odisha'],
       ['PUDUCHERRY','Puducherry'],['PUNJAB','Punjab'],['RAJASTHAN','Rajasthan'],['SIKKIM','Sikkim'],
       ['TAMIL_NADU','Tamil Nadu'],['TELANGANA','Telangana'],['TRIPURA','Tripura'],
       ['UTTAR_PRADESH','Uttar Pradesh'],['UTTARAKHAND','Uttarakhand'],['WEST_BENGAL','West Bengal']],
  // Israel's 6 internationally-recognized districts only -- deliberately excludes the
  // Judea and Samaria Area (West Bank), a genuinely internationally-contested territory,
  // the same political-neutrality reasoning already applied to Russia's city-keyed
  // `state` scheme (see docs/architecture.md "Seed data sourcing").
  IL: [['CENTRAL','Central District'],['HAIFA','Haifa District'],['JERUSALEM','Jerusalem District'],
       ['NORTHERN','Northern District'],['SOUTHERN','Southern District'],['TEL_AVIV','Tel Aviv District']],
  ID: [['ACEH','Aceh'],['BALI','Bali'],['BANTEN','Banten'],['BENGKULU','Bengkulu'],
       ['DI_YOGYAKARTA','DI Yogyakarta'],['DKI_JAKARTA','DKI Jakarta'],['GORONTALO','Gorontalo'],
       ['JAMBI','Jambi'],['JAWA_BARAT','Jawa Barat'],['JAWA_TENGAH','Jawa Tengah'],
       ['JAWA_TIMUR','Jawa Timur'],['KALIMANTAN_BARAT','Kalimantan Barat'],
       ['KALIMANTAN_SELATAN','Kalimantan Selatan'],['KALIMANTAN_TENGAH','Kalimantan Tengah'],
       ['KALIMANTAN_TIMUR','Kalimantan Timur'],['KALIMANTAN_UTARA','Kalimantan Utara'],
       ['KEP_BANGKA_BELITUNG','Kepulauan Bangka Belitung'],['KEP_RIAU','Kepulauan Riau'],
       ['LAMPUNG','Lampung'],['MALUKU','Maluku'],['MALUKU_UTARA','Maluku Utara'],
       ['NUSA_TENGGARA_BARAT','Nusa Tenggara Barat'],['NUSA_TENGGARA_TIMUR','Nusa Tenggara Timur'],
       ['PAPUA','Papua'],['PAPUA_BARAT','Papua Barat'],['PAPUA_BARAT_DAYA','Papua Barat Daya'],
       ['PAPUA_PEGUNUNGAN','Papua Pegunungan'],['PAPUA_SELATAN','Papua Selatan'],
       ['PAPUA_TENGAH','Papua Tengah'],['RIAU','Riau'],['SULAWESI_BARAT','Sulawesi Barat'],
       ['SULAWESI_SELATAN','Sulawesi Selatan'],['SULAWESI_TENGAH','Sulawesi Tengah'],
       ['SULAWESI_TENGGARA','Sulawesi Tenggara'],['SULAWESI_UTARA','Sulawesi Utara'],
       ['SUMATERA_BARAT','Sumatera Barat'],['SUMATERA_SELATAN','Sumatera Selatan'],
       ['SUMATERA_UTARA','Sumatera Utara']],
  TW: [['TAIPEI','Taipei City'],['NEW_TAIPEI','New Taipei City'],['TAOYUAN','Taoyuan City'],
       ['TAICHUNG','Taichung City'],['TAINAN','Tainan City'],['KAOHSIUNG','Kaohsiung City'],
       ['KEELUNG','Keelung City'],['HSINCHU_CITY','Hsinchu City'],['CHIAYI_CITY','Chiayi City'],
       ['HSINCHU_COUNTY','Hsinchu County'],['MIAOLI','Miaoli County'],['CHANGHUA','Changhua County'],
       ['NANTOU','Nantou County'],['YUNLIN','Yunlin County'],['CHIAYI_COUNTY','Chiayi County'],
       ['PINGTUNG','Pingtung County'],['YILAN','Yilan County'],['HUALIEN','Hualien County'],
       ['TAITUNG','Taitung County'],['PENGHU','Penghu County'],['KINMEN','Kinmen County'],
       ['LIENCHIANG','Lienchiang County']],
  // South Africa's 9 real top-level provinces, complete from the start same
  // as every country since the NL state-list-completeness fix -- not just
  // the 5 this first seed-data pass happens to use.
  ZA: [['EASTERN_CAPE','Eastern Cape'],['FREE_STATE','Free State'],['GAUTENG','Gauteng'],
       ['KWAZULU_NATAL','KwaZulu-Natal'],['LIMPOPO','Limpopo'],['MPUMALANGA','Mpumalanga'],
       ['NORTH_WEST','North West'],['NORTHERN_CAPE','Northern Cape'],['WESTERN_CAPE','Western Cape']],
  // Ecuador's 24 real provinces, complete from the start same as every
  // country since the NL state-list-completeness fix.
  EC: [['AZUAY','Azuay'],['BOLIVAR','Bolívar'],['CANAR','Cañar'],['CARCHI','Carchi'],
       ['CHIMBORAZO','Chimborazo'],['COTOPAXI','Cotopaxi'],['EL_ORO','El Oro'],
       ['ESMERALDAS','Esmeraldas'],['GALAPAGOS','Galápagos'],['GUAYAS','Guayas'],
       ['IMBABURA','Imbabura'],['LOJA','Loja'],['LOS_RIOS','Los Ríos'],['MANABI','Manabí'],
       ['MORONA_SANTIAGO','Morona Santiago'],['NAPO','Napo'],['ORELLANA','Orellana'],
       ['PASTAZA','Pastaza'],['PICHINCHA','Pichincha'],['SANTA_ELENA','Santa Elena'],
       ['SANTO_DOMINGO','Santo Domingo de los Tsáchilas'],['SUCUMBIOS','Sucumbíos'],
       ['TUNGURAHUA','Tungurahua'],['ZAMORA_CHINCHIPE','Zamora Chinchipe']],
  // Vietnam's 34 real top-level provinces/centrally-governed cities as of
  // the July 2025 provincial merger (63 -> 34), complete from the start
  // same as every country since the NL state-list-completeness fix.
  VN: [['AN_GIANG','An Giang'],['CA_MAU','Cà Mau'],['CAN_THO','Cần Thơ'],['CAO_BANG','Cao Bằng'],
       ['DA_NANG','Đà Nẵng'],['DAK_LAK','Đắk Lắk'],['DIEN_BIEN','Điện Biên'],['DONG_NAI','Đồng Nai'],
       ['DONG_THAP','Đồng Tháp'],['GIA_LAI','Gia Lai'],['HA_TINH','Hà Tĩnh'],['HAI_PHONG','Hải Phòng'],
       ['HANOI','Hà Nội'],['HO_CHI_MINH','Hồ Chí Minh'],['HUE','Huế'],['HUNG_YEN','Hưng Yên'],
       ['KHANH_HOA','Khánh Hòa'],['LAI_CHAU','Lai Châu'],['LAM_DONG','Lâm Đồng'],['LANG_SON','Lạng Sơn'],
       ['LAO_CAI','Lào Cai'],['NGHE_AN','Nghệ An'],['NINH_BINH','Ninh Bình'],['PHU_THO','Phú Thọ'],
       ['QUANG_NGAI','Quảng Ngãi'],['QUANG_NINH','Quảng Ninh'],['QUANG_TRI','Quảng Trị'],
       ['SON_LA','Sơn La'],['TAY_NINH','Tây Ninh'],['THAI_NGUYEN','Thái Nguyên'],
       ['THANH_HOA','Thanh Hóa'],['TUYEN_QUANG','Tuyên Quang'],['VINH_LONG','Vĩnh Long'],
       ['BAC_NINH','Bắc Ninh']],
  // Lithuania's 10 real counties (apskritys), complete from the start
  // same as every country since the NL state-list-completeness fix.
  LT: [['ALYTUS','Alytus'],['KAUNAS','Kaunas'],['KLAIPEDA','Klaipėda'],['MARIJAMPOLE','Marijampolė'],
       ['PANEVEZYS','Panevėžys'],['SIAULIAI','Šiauliai'],['TAURAGE','Tauragė'],['TELSIAI','Telšiai'],
       ['UTENA','Utena'],['VILNIUS','Vilnius']],
  // Serbia's 25 real top-level districts (Belgrade + Vojvodina's 7 +
  // Central Serbia's 17), deliberately excluding Kosovo and Metohija's
  // 5 districts -- same political-neutrality reasoning already applied
  // to Russia's city-keyed `state` scheme and Israel's exclusion of the
  // West Bank: Kosovo's status is a genuine, internationally contested
  // question this app has no reason to take a position on by drawing it
  // into a public filter list.
  RS: [['BELGRADE','Belgrade'],['SEVERNOBACKI','North Bačka'],['SREDNJEBANATSKI','Central Banat'],
       ['SEVERNOBANATSKI','North Banat'],['JUZNOBANATSKI','South Banat'],['ZAPADNOBACKI','West Bačka'],
       ['JUZNOBACKI','South Bačka'],['SREMSKI','Srem'],['MACVANSKI','Mačva'],['KOLUBARSKI','Kolubara'],
       ['PODUNAVSKI','Podunavlje'],['BRANICEVSKI','Braničevo'],['SUMADIJSKI','Šumadija'],
       ['POMORAVSKI','Pomoravlje'],['BORSKI','Bor'],['ZAJECARSKI','Zaječar'],['ZLATIBORSKI','Zlatibor'],
       ['MORAVICKI','Moravica'],['RASKI','Raška'],['RASINSKI','Rasina'],['NISAVSKI','Nišava'],
       ['TOPLICKI','Toplica'],['PIROTSKI','Pirot'],['JABLANICKI','Jablanica'],['PCINJSKI','Pčinja']],
  // Bolivia's 9 real departments, populated complete from the start
  // same as every country since the NL state-list-completeness fix.
  BO: [['LA_PAZ','La Paz'],['COCHABAMBA','Cochabamba'],['SANTA_CRUZ','Santa Cruz'],['ORURO','Oruro'],
       ['POTOSI','Potosí'],['CHUQUISACA','Chuquisaca'],['TARIJA','Tarija'],['BENI','Beni'],['PANDO','Pando']],
  // Iran's 31 real provinces, populated complete from the start same
  // as every country since the NL state-list-completeness fix.
  IR: [['TEHRAN','Tehran'],['ALBORZ','Alborz'],['QOM','Qom'],['QAZVIN','Qazvin'],['ZANJAN','Zanjan'],
       ['GILAN','Gilan'],['MAZANDARAN','Mazandaran'],['GOLESTAN','Golestan'],['ARDABIL','Ardabil'],
       ['EAST_AZERBAIJAN','East Azerbaijan'],['WEST_AZERBAIJAN','West Azerbaijan'],['KURDISTAN','Kurdistan'],
       ['HAMADAN','Hamadan'],['MARKAZI','Markazi'],['SEMNAN','Semnan'],['NORTH_KHORASAN','North Khorasan'],
       ['RAZAVI_KHORASAN','Razavi Khorasan'],['SOUTH_KHORASAN','South Khorasan'],['ISFAHAN','Isfahan'],
       ['YAZD','Yazd'],['KERMAN','Kerman'],['SISTAN_AND_BALUCHESTAN','Sistan and Baluchestan'],
       ['FARS','Fars'],['BUSHEHR','Bushehr'],['HORMOZGAN','Hormozgan'],['KERMANSHAH','Kermanshah'],
       ['ILAM','Ilam'],['LORESTAN','Lorestan'],['KHUZESTAN','Khuzestan'],
       ['CHAHARMAHAL_AND_BAKHTIARI','Chaharmahal and Bakhtiari'],
       ['KOHGILUYEH_AND_BOYER_AHMAD','Kohgiluyeh and Boyer-Ahmad']],
  // Estonia's 15 real counties (maakonnad), populated complete from the
  // start same as every country since the NL state-list-completeness fix.
  EE: [['HARJU','Harju'],['TARTU','Tartu'],['HIIU','Hiiu'],['IDA_VIRU','Ida-Viru'],['JARVA','Järva'],
       ['JOGEVA','Jõgeva'],['LAANE','Lääne'],['LAANE_VIRU','Lääne-Viru'],['PARNU','Pärnu'],
       ['POLVA','Põlva'],['RAPLA','Rapla'],['SAARE','Saare'],['VALGA','Valga'],['VILJANDI','Viljandi'],
       ['VORU','Võru']],
  // Malaysia's 13 states + 3 federal territories, populated complete
  // from the start same as every country since the NL fix.
  MY: [['JOHOR','Johor'],['KEDAH','Kedah'],['KELANTAN','Kelantan'],['MALACCA','Malacca'],
       ['NEGERI_SEMBILAN','Negeri Sembilan'],['PAHANG','Pahang'],['PENANG','Penang'],['PERAK','Perak'],
       ['PERLIS','Perlis'],['SABAH','Sabah'],['SARAWAK','Sarawak'],['SELANGOR','Selangor'],
       ['TERENGGANU','Terengganu'],['KUALA_LUMPUR','Kuala Lumpur'],['LABUAN','Labuan'],
       ['PUTRAJAYA','Putrajaya']],
  // Thailand's 76 provinces + Bangkok (77 total), populated complete
  // from the start same as every country since the NL fix.
  TH: [['BANGKOK','Bangkok'],['AMNAT_CHAROEN','Amnat Charoen'],['ANG_THONG','Ang Thong'],
       ['BUENG_KAN','Bueng Kan'],['BURIRAM','Buriram'],['CHACHOENGSAO','Chachoengsao'],
       ['CHAI_NAT','Chai Nat'],['CHAIYAPHUM','Chaiyaphum'],['CHANTHABURI','Chanthaburi'],
       ['CHIANG_MAI','Chiang Mai'],['CHIANG_RAI','Chiang Rai'],['CHONBURI','Chonburi'],
       ['CHUMPHON','Chumphon'],['KALASIN','Kalasin'],['KAMPHAENG_PHET','Kamphaeng Phet'],
       ['KANCHANABURI','Kanchanaburi'],['KHON_KAEN','Khon Kaen'],['KRABI','Krabi'],
       ['LAMPANG','Lampang'],['LAMPHUN','Lamphun'],['LOEI','Loei'],['LOPBURI','Lopburi'],
       ['MAE_HONG_SON','Mae Hong Son'],['MAHA_SARAKHAM','Maha Sarakham'],['MUKDAHAN','Mukdahan'],
       ['NAKHON_NAYOK','Nakhon Nayok'],['NAKHON_PATHOM','Nakhon Pathom'],
       ['NAKHON_PHANOM','Nakhon Phanom'],['NAKHON_RATCHASIMA','Nakhon Ratchasima'],
       ['NAKHON_SAWAN','Nakhon Sawan'],['NAKHON_SI_THAMMARAT','Nakhon Si Thammarat'],
       ['NAN','Nan'],['NARATHIWAT','Narathiwat'],['NONG_BUA_LAMPHU','Nong Bua Lamphu'],
       ['NONG_KHAI','Nong Khai'],['NONTHABURI','Nonthaburi'],['PATHUM_THANI','Pathum Thani'],
       ['PATTANI','Pattani'],['PHANG_NGA','Phang Nga'],['PHATTHALUNG','Phatthalung'],
       ['PHAYAO','Phayao'],['PHETCHABUN','Phetchabun'],['PHETCHABURI','Phetchaburi'],
       ['PHICHIT','Phichit'],['PHITSANULOK','Phitsanulok'],
       ['PHRA_NAKHON_SI_AYUTTHAYA','Phra Nakhon Si Ayutthaya'],['PHRAE','Phrae'],
       ['PHUKET','Phuket'],['PRACHINBURI','Prachinburi'],['PRACHUAP_KHIRI_KHAN','Prachuap Khiri Khan'],
       ['RANONG','Ranong'],['RATCHABURI','Ratchaburi'],['RAYONG','Rayong'],['ROI_ET','Roi Et'],
       ['SA_KAEO','Sa Kaeo'],['SAKON_NAKHON','Sakon Nakhon'],['SAMUT_PRAKAN','Samut Prakan'],
       ['SAMUT_SAKHON','Samut Sakhon'],['SAMUT_SONGKHRAM','Samut Songkhram'],['SARABURI','Saraburi'],
       ['SATUN','Satun'],['SING_BURI','Sing Buri'],['SISAKET','Sisaket'],['SONGKHLA','Songkhla'],
       ['SUKHOTHAI','Sukhothai'],['SUPHAN_BURI','Suphan Buri'],['SURAT_THANI','Surat Thani'],
       ['SURIN','Surin'],['TAK','Tak'],['TRANG','Trang'],['TRAT','Trat'],
       ['UBON_RATCHATHANI','Ubon Ratchathani'],['UDON_THANI','Udon Thani'],
       ['UTHAI_THANI','Uthai Thani'],['UTTARADIT','Uttaradit'],['YALA','Yala'],['YASOTHON','Yasothon']],
  // Ukraine's 24 oblasts + the Autonomous Republic of Crimea + Kyiv and
  // Sevastopol (special-status cities) -- 27 total, Ukraine's own
  // internationally-recognized constitutional territory (unlike
  // Russia's or Serbia's state lists, which deliberately exclude
  // contested territory belonging to a *different* country, including
  // Crimea here doesn't take a side -- it's simply Ukraine's own
  // official division list).
  UA: [['CHERKASY','Cherkasy Oblast'],['CHERNIHIV','Chernihiv Oblast'],['CHERNIVTSI','Chernivtsi Oblast'],
       ['DNIPROPETROVSK','Dnipropetrovsk Oblast'],['DONETSK','Donetsk Oblast'],
       ['IVANO_FRANKIVSK','Ivano-Frankivsk Oblast'],['KHARKIV','Kharkiv Oblast'],['KHERSON','Kherson Oblast'],
       ['KHMELNYTSKYI','Khmelnytskyi Oblast'],['KIROVOHRAD','Kirovohrad Oblast'],
       ['KYIV_OBLAST','Kyiv Oblast'],['LUHANSK','Luhansk Oblast'],['LVIV','Lviv Oblast'],
       ['MYKOLAIV','Mykolaiv Oblast'],['ODESA','Odesa Oblast'],['POLTAVA','Poltava Oblast'],
       ['RIVNE','Rivne Oblast'],['SUMY','Sumy Oblast'],['TERNOPIL','Ternopil Oblast'],
       ['VINNYTSIA','Vinnytsia Oblast'],['VOLYN','Volyn Oblast'],['ZAKARPATTIA','Zakarpattia Oblast'],
       ['ZAPORIZHZHIA','Zaporizhzhia Oblast'],['ZHYTOMYR','Zhytomyr Oblast'],
       ['CRIMEA','Autonomous Republic of Crimea'],['KYIV','Kyiv'],['SEVASTOPOL','Sevastopol']],
  // Slovakia's 8 real kraje (regions), populated complete from the start
  // same as every country since the NL state-list-completeness fix.
  SK: [['BRATISLAVSKY','Bratislavský'],['TRNAVSKY','Trnavský'],['TRENCIANSKY','Trenčiansky'],
       ['NITRIANSKY','Nitriansky'],['ZILINSKY','Žilinský'],['BANSKOBYSTRICKY','Banskobystrický'],
       ['PRESOVSKY','Prešovský'],['KOSICKY','Košický']],
  // Cyprus's 6 official Republic of Cyprus districts -- the standard,
  // internationally-recognized administrative division used by the UN
  // and virtually every country (Northern Cyprus/the TRNC is recognized
  // only by Turkey), not a contested-territory judgment call the way
  // Kosovo/West Bank/Crimea were elsewhere in this file.
  CY: [['NICOSIA','Nicosia'],['LIMASSOL','Limassol'],['LARNACA','Larnaca'],
       ['FAMAGUSTA','Famagusta'],['PAPHOS','Paphos'],['KYRENIA','Kyrenia']],
  // Panama's 10 real provinces plus its 5 indigenous comarcas, populated
  // complete from the start same as every country since the NL fix.
  PA: [['CHIRIQUI','Chiriquí'],['PANAMA','Panamá'],['PANAMA_OESTE','Panamá Oeste'],
       ['BOCAS_DEL_TORO','Bocas del Toro'],['COCLE','Coclé'],['COLON','Colón'],
       ['DARIEN','Darién'],['HERRERA','Herrera'],['LOS_SANTOS','Los Santos'],
       ['VERAGUAS','Veraguas'],['GUNA_YALA','Comarca Guna Yala'],
       ['EMBERA_WOUNAAN','Comarca Emberá-Wounaan'],['NGABE_BUGLE','Comarca Ngäbe-Buglé'],
       ['KUNA_MADUNGANDI','Comarca Kuna de Madungandí'],['KUNA_WARGANDI','Comarca Kuna de Wargandí']],
  // Peru's 25 real regions (24 departments + the Constitutional
  // Province of Callao), populated complete from the start.
  PE: [['LIMA','Lima'],['AREQUIPA','Arequipa'],['AMAZONAS','Amazonas'],['ANCASH','Áncash'],
       ['APURIMAC','Apurímac'],['AYACUCHO','Ayacucho'],['CAJAMARCA','Cajamarca'],
       ['CALLAO','Callao'],['CUSCO','Cusco'],['HUANCAVELICA','Huancavelica'],
       ['HUANUCO','Huánuco'],['ICA','Ica'],['JUNIN','Junín'],['LA_LIBERTAD','La Libertad'],
       ['LAMBAYEQUE','Lambayeque'],['LORETO','Loreto'],['MADRE_DE_DIOS','Madre de Dios'],
       ['MOQUEGUA','Moquegua'],['PASCO','Pasco'],['PIURA','Piura'],['PUNO','Puno'],
       ['SAN_MARTIN','San Martín'],['TACNA','Tacna'],['TUMBES','Tumbes'],['UCAYALI','Ucayali']],
  // Turkey's 81 real provinces (il), populated complete from the start
  // same as every country since the NL fix.
  TR: [['ADANA','Adana'],['ADIYAMAN','Adıyaman'],['AFYONKARAHISAR','Afyonkarahisar'],
       ['AGRI','Ağrı'],['AMASYA','Amasya'],['ANKARA','Ankara'],['ANTALYA','Antalya'],
       ['ARTVIN','Artvin'],['AYDIN','Aydın'],['BALIKESIR','Balıkesir'],['BILECIK','Bilecik'],
       ['BINGOL','Bingöl'],['BITLIS','Bitlis'],['BOLU','Bolu'],['BURDUR','Burdur'],
       ['BURSA','Bursa'],['CANAKKALE','Çanakkale'],['CANKIRI','Çankırı'],['CORUM','Çorum'],
       ['DENIZLI','Denizli'],['DIYARBAKIR','Diyarbakır'],['EDIRNE','Edirne'],
       ['ELAZIG','Elazığ'],['ERZINCAN','Erzincan'],['ERZURUM','Erzurum'],
       ['ESKISEHIR','Eskişehir'],['GAZIANTEP','Gaziantep'],['GIRESUN','Giresun'],
       ['GUMUSHANE','Gümüşhane'],['HAKKARI','Hakkari'],['HATAY','Hatay'],
       ['ISPARTA','Isparta'],['MERSIN','Mersin'],['ISTANBUL','İstanbul'],['IZMIR','İzmir'],
       ['KARS','Kars'],['KASTAMONU','Kastamonu'],['KAYSERI','Kayseri'],
       ['KIRKLARELI','Kırklareli'],['KIRSEHIR','Kırşehir'],['KOCAELI','Kocaeli'],
       ['KONYA','Konya'],['KUTAHYA','Kütahya'],['MALATYA','Malatya'],['MANISA','Manisa'],
       ['KAHRAMANMARAS','Kahramanmaraş'],['MARDIN','Mardin'],['MUGLA','Muğla'],
       ['MUS','Muş'],['NEVSEHIR','Nevşehir'],['NIGDE','Niğde'],['ORDU','Ordu'],
       ['RIZE','Rize'],['SAKARYA','Sakarya'],['SAMSUN','Samsun'],['SIIRT','Siirt'],
       ['SINOP','Sinop'],['SIVAS','Sivas'],['TEKIRDAG','Tekirdağ'],['TOKAT','Tokat'],
       ['TRABZON','Trabzon'],['TUNCELI','Tunceli'],['SANLIURFA','Şanlıurfa'],
       ['USAK','Uşak'],['VAN','Van'],['YOZGAT','Yozgat'],['ZONGULDAK','Zonguldak'],
       ['AKSARAY','Aksaray'],['BAYBURT','Bayburt'],['KARAMAN','Karaman'],
       ['KIRIKKALE','Kırıkkale'],['BATMAN','Batman'],['SIRNAK','Şırnak'],
       ['BARTIN','Bartın'],['ARDAHAN','Ardahan'],['IGDIR','Iğdır'],['YALOVA','Yalova'],
       ['KARABUK','Karabük'],['KILIS','Kilis'],['OSMANIYE','Osmaniye'],['DUZCE','Düzce']],
  // Latvia's 7 republican cities (valstspilsētas) plus 36 municipalities
  // (novadi) as of the 2021 administrative-territorial reform, populated
  // complete from the start same as every country since the NL fix.
  LV: [['RIGA','Rīga'],['DAUGAVPILS','Daugavpils'],['JELGAVA','Jelgava'],
       ['JEKABPILS','Jēkabpils'],['JURMALA','Jūrmala'],['LIEPAJA','Liepāja'],
       ['REZEKNE','Rēzekne'],['ADAZU','Ādažu novads'],['AIZKRAUKLES','Aizkraukles novads'],
       ['ALUKSNES','Alūksnes novads'],['AUGSDAUGAVAS','Augšdaugavas novads'],
       ['BALVU','Balvu novads'],['BAUSKAS','Bauskas novads'],['CESU','Cēsu novads'],
       ['DIENVIDKURZEMES','Dienvidkurzemes novads'],['DOBELES','Dobeles novads'],
       ['GULBENES','Gulbenes novads'],['JEKABPILS_NOVADS','Jēkabpils novads'],
       ['JELGAVAS_NOVADS','Jelgavas novads'],['KEKAVAS','Ķekavas novads'],
       ['KRASLAVAS','Krāslavas novads'],['KULDIGAS','Kuldīgas novads'],
       ['LIMBAZU','Limbažu novads'],['LIVANU','Līvānu novads'],['LUDZAS','Ludzas novads'],
       ['MADONAS','Madonas novads'],['MARUPES','Mārupes novads'],['OGRES','Ogres novads'],
       ['OLAINES','Olaines novads'],['PREILU','Preiļu novads'],
       ['REZEKNES_NOVADS','Rēzeknes novads'],['ROPAZU','Ropažu novads'],
       ['SALASPILS','Salaspils novads'],['SALDUS','Saldus novads'],
       ['SAULKRASTU','Saulkrastu novads'],['SIGULDAS','Siguldas novads'],
       ['SMILTENES','Smiltenes novads'],['TALSU','Talsu novads'],['TUKUMA','Tukuma novads'],
       ['VALKAS','Valkas novads'],['VALMIERAS','Valmieras novads'],
       ['VARAKLANU','Varakļānu novads'],['VENTSPILS','Ventspils novads']],
  // Singapore's 5 Community Development Council (CDC) districts,
  // populated complete from the start same as every country since the
  // NL fix.
  SG: [['CENTRAL','Central Singapore'],['NORTH_EAST','North East'],
       ['NORTH_WEST','North West'],['SOUTH_EAST','South East'],
       ['SOUTH_WEST','South West']],
  // Bosnia and Herzegovina's real top-level divisions: the 10 cantons
  // of the Federation of BiH, Republika Srpska (its own entity, not
  // internally cantonized), and Brčko District -- populated complete
  // from the start same as every country since the NL fix.
  BA: [['UNA_SANA','Una-Sana Canton'],['POSAVINA','Posavina Canton'],
       ['TUZLA','Tuzla Canton'],['ZENICA_DOBOJ','Zenica-Doboj Canton'],
       ['BOSNIAN_PODRINJE','Bosnian Podrinje Canton'],
       ['CENTRAL_BOSNIA','Central Bosnia Canton'],
       ['HERZEGOVINA_NERETVA','Herzegovina-Neretva Canton'],
       ['WEST_HERZEGOVINA','West Herzegovina Canton'],
       ['SARAJEVO_CANTON','Sarajevo Canton'],['CANTON_10','Canton 10'],
       ['REPUBLIKA_SRPSKA','Republika Srpska'],['BRCKO','Brčko District']],
  // Andorra's 7 real parishes (parròquies), populated complete from the
  // start same as every country since the NL fix.
  AD: [['ANDORRA_LA_VELLA','Andorra la Vella'],['CANILLO','Canillo'],
       ['ENCAMP','Encamp'],['ESCALDES_ENGORDANY','Escaldes-Engordany'],
       ['LA_MASSANA','La Massana'],['ORDINO','Ordino'],
       ['SANT_JULIA_DE_LORIA',"Sant Julià de Lòria"]],
  // United Arab Emirates' 7 emirates.
  AE: [['ABU_DHABI','Abu Dhabi'],['DUBAI','Dubai'],['SHARJAH','Sharjah'],['AJMAN','Ajman'],
       ['UMM_AL_QUWAIN','Umm Al Quwain'],['RAS_AL_KHAIMAH','Ras Al Khaimah'],['FUJAIRAH','Fujairah']],
  // Georgia (the country) -- Tbilisi + 9 regions + the 2 autonomous republics
  // (Adjara, Abkhazia). Abkhazia is included as Georgia's own internationally
  // recognised territory, the same call made for Crimea under Ukraine.
  GE: [['TBILISI','Tbilisi'],['ADJARA','Adjara'],['ABKHAZIA','Abkhazia'],['GURIA','Guria'],
       ['IMERETI','Imereti'],['KAKHETI','Kakheti'],['KVEMO_KARTLI','Kvemo Kartli'],
       ['MTSKHETA_MTIANETI','Mtskheta-Mtianeti'],['RACHA_LECHKHUMI','Racha-Lechkhumi and Kvemo Svaneti'],
       ['SAMEGRELO','Samegrelo-Zemo Svaneti'],['SAMTSKHE_JAVAKHETI','Samtskhe-Javakheti'],
       ['SHIDA_KARTLI','Shida Kartli']],
  // Luxembourg's 12 cantons.
  LU: [['CAPELLEN','Capellen'],['CLERVAUX','Clervaux'],['DIEKIRCH','Diekirch'],['ECHTERNACH','Echternach'],
       ['ESCH_SUR_ALZETTE','Esch-sur-Alzette'],['GREVENMACHER','Grevenmacher'],['LUXEMBOURG','Luxembourg'],
       ['MERSCH','Mersch'],['REDANGE','Redange'],['REMICH','Remich'],['VIANDEN','Vianden'],['WILTZ','Wiltz']],
  // Slovenia's 12 statistical regions.
  SI: [['POMURSKA','Mura'],['PODRAVSKA','Drava'],['KOROSKA','Carinthia'],['SAVINJSKA','Savinja'],['ZASAVSKA','Central Sava'],['POSAVSKA','Lower Sava'],
       ['JUGOVZHODNA','Southeast Slovenia'],['OSREDNJESLOVENSKA','Central Slovenia'],['GORENJSKA','Upper Carniola'],['PRIMORSKO_NOTRANJSKA','Littoral-Inner Carniola'],
       ['GORISKA','Gorizia'],['OBALNO_KRASKA','Coastal-Karst']],
  // Kazakhstan: 3 cities of republican significance + 17 regions. Almaty city and Almaty Region are separate divisions.
  KZ: [['ASTANA','Astana'],['ALMATY_CITY','Almaty'],['SHYMKENT','Shymkent'],['ABAI','Abai'],['AKMOLA','Akmola'],['AKTOBE','Aktobe'],['ALMATY_REGION','Almaty Region'],
       ['ATYRAU','Atyrau'],['EAST_KAZAKHSTAN','East Kazakhstan'],['JAMBYL','Jambyl'],['JETISU','Jetisu'],['KARAGANDA','Karaganda'],['KOSTANAY','Kostanay'],
       ['KYZYLORDA','Kyzylorda'],['MANGYSTAU','Mangystau'],['NORTH_KAZAKHSTAN','North Kazakhstan'],['PAVLODAR','Pavlodar'],['TURKISTAN','Turkistan'],
       ['ULYTAU','Ulytau'],['WEST_KAZAKHSTAN','West Kazakhstan']],
  // Costa Rica's 7 provinces.
  CR: [['SAN_JOSE','San José'],['ALAJUELA','Alajuela'],['CARTAGO','Cartago'],['HEREDIA','Heredia'],['GUANACASTE','Guanacaste'],['PUNTARENAS','Puntarenas'],['LIMON','Limón']],
  // Belarus: 6 regions plus Minsk city (its own division, separate from Minsk Region).
  BY: [['BREST','Brest Region'],['GOMEL','Gomel Region'],['GRODNO','Grodno Region'],['MINSK_CITY','Minsk'],['MINSK_REGION','Minsk Region'],['MOGILEV','Mogilev Region'],['VITEBSK','Vitebsk Region']],
  // Uruguay's 19 departments.
  UY: [['ARTIGAS','Artigas'],['CANELONES','Canelones'],['CERRO_LARGO','Cerro Largo'],['COLONIA','Colonia'],['DURAZNO','Durazno'],['FLORES','Flores'],['FLORIDA','Florida'],
       ['LAVALLEJA','Lavalleja'],['MALDONADO','Maldonado'],['MONTEVIDEO','Montevideo'],['PAYSANDU','Paysandú'],['RIO_NEGRO','Río Negro'],['RIVERA','Rivera'],['ROCHA','Rocha'],
       ['SALTO','Salto'],['SAN_JOSE','San José'],['SORIANO','Soriano'],['TACUAREMBO','Tacuarembó'],['TREINTA_Y_TRES','Treinta y Tres']],
  // Saudi Arabia's 13 administrative regions.
  SA: [['RIYADH','Riyadh Region'],['MAKKAH','Makkah Region'],['MADINAH','Madinah Region'],['QASSIM','Al-Qassim Region'],['EASTERN','Eastern Province'],['ASIR','Asir Region'],
       ['TABUK','Tabuk Region'],['HAIL','Ha\'il Region'],['NORTHERN_BORDERS','Northern Borders Region'],['JAZAN','Jazan Region'],['NAJRAN','Najran Region'],['BAHAH','Al Bahah Region'],['JAWF','Al Jawf Region']],
  // Hong Kong's 18 districts.
  HK: [['CENTRAL_WESTERN','Central and Western'],['EASTERN','Eastern'],['SOUTHERN','Southern'],['WAN_CHAI','Wan Chai'],['KOWLOON_CITY','Kowloon City'],
       ['KWUN_TONG','Kwun Tong'],['SHAM_SHUI_PO','Sham Shui Po'],['WONG_TAI_SIN','Wong Tai Sin'],['YAU_TSIM_MONG','Yau Tsim Mong'],['ISLANDS','Islands'],
       ['KWAI_TSING','Kwai Tsing'],['NORTH','North'],['SAI_KUNG','Sai Kung'],['SHA_TIN','Sha Tin'],['TAI_PO','Tai Po'],
       ['TSUEN_WAN','Tsuen Wan'],['TUEN_MUN','Tuen Mun'],['YUEN_LONG','Yuen Long']],
  // Egypt's 27 governorates.
  EG: [['ALEXANDRIA','Alexandria'],['ASWAN','Aswan'],['ASYUT','Asyut'],['BEHEIRA','Beheira'],['BENI_SUEF','Beni Suef'],['CAIRO','Cairo'],
       ['DAKAHLIA','Dakahlia'],['DAMIETTA','Damietta'],['FAIYUM','Faiyum'],['GHARBIA','Gharbia'],['GIZA','Giza'],['ISMAILIA','Ismailia'],
       ['KAFR_EL_SHEIKH','Kafr el-Sheikh'],['LUXOR','Luxor'],['MATROUH','Matrouh'],['MINYA','Minya'],['MONUFIA','Monufia'],['NEW_VALLEY','New Valley'],
       ['NORTH_SINAI','North Sinai'],['PORT_SAID','Port Said'],['QALYUBIA','Qalyubia'],['QENA','Qena'],['RED_SEA','Red Sea'],['SHARQIA','Sharqia'],
       ['SOHAG','Sohag'],['SOUTH_SINAI','South Sinai'],['SUEZ','Suez']],
  // Kenya's 47 counties.
  KE: [['BARINGO','Baringo'],['BOMET','Bomet'],['BUNGOMA','Bungoma'],['BUSIA','Busia'],['ELGEYO_MARAKWET','Elgeyo-Marakwet'],['EMBU','Embu'],
       ['GARISSA','Garissa'],['HOMA_BAY','Homa Bay'],['ISIOLO','Isiolo'],['KAJIADO','Kajiado'],['KAKAMEGA','Kakamega'],['KERICHO','Kericho'],
       ['KIAMBU','Kiambu'],['KILIFI','Kilifi'],['KIRINYAGA','Kirinyaga'],['KISII','Kisii'],['KISUMU','Kisumu'],['KITUI','Kitui'],
       ['KWALE','Kwale'],['LAIKIPIA','Laikipia'],['LAMU','Lamu'],['MACHAKOS','Machakos'],['MAKUENI','Makueni'],['MANDERA','Mandera'],
       ['MARSABIT','Marsabit'],['MERU','Meru'],['MIGORI','Migori'],['MOMBASA','Mombasa'],['MURANGA','Murang\'a'],['NAIROBI','Nairobi'],
       ['NAKURU','Nakuru'],['NANDI','Nandi'],['NAROK','Narok'],['NYAMIRA','Nyamira'],['NYANDARUA','Nyandarua'],['NYERI','Nyeri'],
       ['SAMBURU','Samburu'],['SIAYA','Siaya'],['TAITA_TAVETA','Taita-Taveta'],['TANA_RIVER','Tana River'],['THARAKA_NITHI','Tharaka-Nithi'],['TRANS_NZOIA','Trans Nzoia'],
       ['TURKANA','Turkana'],['UASIN_GISHU','Uasin Gishu'],['VIHIGA','Vihiga'],['WAJIR','Wajir'],['WEST_POKOT','West Pokot']],
  // Qatar's 8 municipalities.
  QA: [['AD_DAWHAH','Doha'],['AL_RAYYAN','Al Rayyan'],['AL_WAKRAH','Al Wakrah'],['AL_KHOR','Al Khor and Al Thakhira'],
       ['UMM_SALAL','Umm Salal'],['AL_DAAYEN','Al Daayen'],['AL_SHAMAL','Al Shamal'],['AL_SHAHANIYA','Al Shahaniya']],
  // Armenia's 10 provinces (marzer) plus Yerevan.
  AM: [['ARAGATSOTN','Aragatsotn'],['ARARAT','Ararat'],['ARMAVIR','Armavir'],['GEGHARKUNIK','Gegharkunik'],
       ['KOTAYK','Kotayk'],['LORI','Lori'],['SHIRAK','Shirak'],['SYUNIK','Syunik'],
       ['TAVUSH','Tavush'],['VAYOTS_DZOR','Vayots Dzor'],['YEREVAN','Yerevan']],
  // Lebanon's 8 governorates.
  LB: [['BEIRUT','Beirut'],['MOUNT_LEBANON','Mount Lebanon'],['NORTH','North'],['SOUTH','South'],
       ['BEKAA','Bekaa'],['NABATIEH','Nabatieh'],['AKKAR','Akkar'],['BAALBEK_HERMEL','Baalbek-Hermel']],
  // Jordan's 12 governorates.
  JO: [['AMMAN','Amman'],['BALQA','Balqa'],['ZARQA','Zarqa'],['MADABA','Madaba'],
       ['IRBID','Irbid'],['MAFRAQ','Mafraq'],['JERASH','Jerash'],['AJLOUN','Ajloun'],
       ['KARAK','Karak'],['TAFILAH','Tafilah'],['MAAN','Ma\'an'],['AQABA','Aqaba']],
  // Nepal's 7 provinces.
  NP: [['KOSHI','Koshi'],['MADHESH','Madhesh'],['BAGMATI','Bagmati'],['GANDAKI','Gandaki'],
       ['LUMBINI','Lumbini'],['KARNALI','Karnali'],['SUDURPASHCHIM','Sudurpashchim']],
  // Guatemala's 22 departments.
  GT: [['ALTA_VERAPAZ','Alta Verapaz'],['BAJA_VERAPAZ','Baja Verapaz'],['CHIMALTENANGO','Chimaltenango'],['CHIQUIMULA','Chiquimula'],
       ['EL_PROGRESO','El Progreso'],['ESCUINTLA','Escuintla'],['GUATEMALA','Guatemala'],['HUEHUETENANGO','Huehuetenango'],
       ['IZABAL','Izabal'],['JALAPA','Jalapa'],['JUTIAPA','Jutiapa'],['PETEN','Petén'],
       ['QUETZALTENANGO','Quetzaltenango'],['QUICHE','Quiché'],['RETALHULEU','Retalhuleu'],['SACATEPEQUEZ','Sacatepéquez'],
       ['SAN_MARCOS','San Marcos'],['SANTA_ROSA','Santa Rosa'],['SOLOLA','Sololá'],['SUCHITEPEQUEZ','Suchitepéquez'],
       ['TOTONICAPAN','Totonicapán'],['ZACAPA','Zacapa']],
  // Montenegro's 25 municipalities.
  ME: [['ANDRIJEVICA','Andrijevica'],['BAR','Bar'],['BERANE','Berane'],['BIJELO_POLJE','Bijelo Polje'],
       ['BUDVA','Budva'],['CETINJE','Cetinje'],['DANILOVGRAD','Danilovgrad'],['GUSINJE','Gusinje'],
       ['HERCEG_NOVI','Herceg Novi'],['KOLASIN','Kolašin'],['KOTOR','Kotor'],['MOJKOVAC','Mojkovac'],
       ['NIKSIC','Nikšić'],['PETNJICA','Petnjica'],['PLAV','Plav'],['PLUZINE','Plužine'],
       ['PLJEVLJA','Pljevlja'],['PODGORICA','Podgorica'],['ROZAJE','Rožaje'],['SAVNIK','Šavnik'],
       ['TIVAT','Tivat'],['TUZI','Tuzi'],['ULCINJ','Ulcinj'],['ZABLJAK','Žabljak'],
       ['ZETA','Zeta']],
  // Mongolia: Ulaanbaatar plus the 21 aimags.
  MN: [['ULAANBAATAR','Ulaanbaatar'],['ARKHANGAI','Arkhangai'],['BAYAN_OLGII','Bayan-Ölgii'],['BAYANKHONGOR','Bayankhongor'],
       ['BULGAN','Bulgan'],['DARKHAN_UUL','Darkhan-Uul'],['DORNOD','Dornod'],['DORNOGOVI','Dornogovi'],
       ['DUNDGOVI','Dundgovi'],['GOVI_ALTAI','Govi-Altai'],['GOVISUMBER','Govisümber'],['KHENTII','Khentii'],
       ['KHOVD','Khovd'],['KHOVSGOL','Khövsgöl'],['ORKHON','Orkhon'],['OVORKHANGAI','Övörkhangai'],
       ['OMNOGOVI','Ömnögovi'],['SELENGE','Selenge'],['SUKHBAATAR','Sükhbaatar'],['TOV','Töv'],
       ['UVS','Uvs'],['ZAVKHAN','Zavkhan']],
  // Oman's 11 governorates.
  OM: [['MUSCAT','Muscat'],['DHOFAR','Dhofar'],['MUSANDAM','Musandam'],['AL_BURAIMI','Al Buraimi'],
       ['AD_DAKHILIYAH','Ad Dakhiliyah'],['AL_BATINAH_NORTH','Al Batinah North'],['AL_BATINAH_SOUTH','Al Batinah South'],['ASH_SHARQIYAH_NORTH','Ash Sharqiyah North'],
       ['ASH_SHARQIYAH_SOUTH','Ash Sharqiyah South'],['AD_DHAHIRAH','Ad Dhahirah'],['AL_WUSTA','Al Wusta']],
  // Paraguay: the Asuncion capital district plus 17 departments.
  PY: [['ASUNCION','Asunción'],['CONCEPCION','Concepción'],['SAN_PEDRO','San Pedro'],['CORDILLERA','Cordillera'],
       ['GUAIRA','Guairá'],['CAAGUAZU','Caaguazú'],['CAAZAPA','Caazapá'],['ITAPUA','Itapúa'],
       ['MISIONES','Misiones'],['PARAGUARI','Paraguarí'],['ALTO_PARANA','Alto Paraná'],['CENTRAL','Central'],
       ['NEEMBUCU','Ñeembucú'],['AMAMBAY','Amambay'],['CANINDEYU','Canindeyú'],['PRESIDENTE_HAYES','Presidente Hayes'],
       ['BOQUERON','Boquerón'],['ALTO_PARAGUAY','Alto Paraguay']]
};
